import React, { createContext, useContext, useState, useEffect } from 'react';

interface LanguageContextType {
  language: 'en' | 'nl';
  setLanguage: (lang: 'en' | 'nl') => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.howItWorks': 'How It Works',
    'nav.examples': 'Examples',
    'nav.merchants': 'For Webshops',
    'nav.partners': 'For Partners',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.joinBeta': 'Join Beta',
    
    // Home Page
    'home.hero.title': 'Turn your Thank-You Page into Instant Revenue.',
    'home.hero.subtitle': 'AmplifAI shows highly relevant add-ons from your catalog and trusted partners—right after purchase.',
    'home.hero.joinBeta': 'Join the Beta',
    'home.hero.seeExamples': 'See Examples',
    'home.seeInAction': 'See it in action',
    'home.demo.subtitle': 'This is how your thank-you page transforms with AmplifAI',
    'home.results.title': 'Results that speak for themselves',
    'home.results.subtitle': 'Our beta merchants are already seeing incredible results with AmplifAI',
    'home.metrics.aov.label': 'Average AOV Increase',
    'home.metrics.aov.desc': 'Typical lift in average order value within 30 days',
    'home.metrics.extraRevenue.label': 'Extra Revenue',
    'home.metrics.extraRevenue.desc': 'Additional revenue per completed order',
    'home.metrics.attachRate.label': 'Attach Rate',
    'home.metrics.attachRate.desc': 'Customers who add at least one offer',
    'home.features.lightning.title': 'Lightning Fast',
    'home.features.lightning.desc': 'Shows up instantly after purchase. No delays, no friction.',
    'home.features.ai.title': 'AI-Powered Matching',
    'home.features.ai.desc': 'Smart algorithms find the perfect complementary products.',
    'home.features.brand.title': 'Brand Safe',
    'home.features.brand.desc': 'Full control over what partners can offer your customers.',
    'home.socialProof.title': 'Trusted by leading e-commerce brands',
    'home.cta.title': 'Ready to transform your thank-you page?',
    'home.cta.subtitle': 'Join hundreds of merchants already boosting their revenue with AmplifAI. Setup takes less than 5 minutes.',
    'home.cta.button': 'Get Started Today',
    
    // Widget Demo
    'widget.title': 'Perfect additions for you',
    'widget.subtitle': 'Curated based on your purchase',
    'widget.orderConfirmed': 'Order Confirmed!',
    'widget.thankYou': 'Thank you for your purchase of the',
    'widget.yourStore': 'Your Store',
    'widget.partners': 'Partners',
    'widget.addInOneClick': 'Add in 1 click',
    'widget.added': 'Added!',
    'widget.byAmplif': 'by AmplifAI',
    
    // Examples Page
    'examples.title': 'Perfect Pairing Examples',
    'examples.subtitle': 'See how AmplifAI creates perfect product pairings across different categories. Each pairing is intelligently matched to maximize value for your customers.',
    'examples.categories.title': 'Offer Categories',
    'examples.categories.subtitle': 'AmplifAI supports multiple types of complementary offers to maximize your revenue potential',
    'examples.tryInDemo': 'Try in Demo',
    'examples.activePairings': 'Active Pairings',
    'examples.examplePairingsTitle': 'Example Pairings',
    'examples.clickToSee': 'Click to see perfect add-ons',
    'examples.perfectAddons': 'Perfect Add-ons',
    'examples.for': 'for',
    'examples.successStories.title': 'Success Stories',
    'examples.successStories.subtitle': 'Real results from merchants using these exact pairings',
    'examples.cta.title': 'Ready to create your own perfect pairings?',
    'examples.cta.subtitle': 'Start with our proven pairing templates and customize them for your store. Our team will help you identify the best opportunities.',
    'examples.cta.startBeta': 'Start Your Beta',
    'examples.cta.tryDemo': 'Try the Demo',
    'examples.grid.subtitle': 'Click any card to see the perfect complementary offers. Each pairing is designed to add genuine value to your customers.',
    
    // How It Works
    'howItWorks.title': 'How AmplifAI Works',
    'howItWorks.subtitle': 'Transform your checkout completion into a revenue opportunity with just 3 simple steps',
    'howItWorks.step1.title': 'Install',
    'howItWorks.step1.desc': 'Add our lightweight snippet to your thank-you page in under 5 minutes',
    'howItWorks.step1.details': 'Add our lightweight widget to your thank-you page with a simple code snippet or install our pre-built extensions for popular platforms like Shopify, WooCommerce, and BigCommerce. Takes less than 5 minutes.',
    'howItWorks.step2.title': 'Match', 
    'howItWorks.step2.desc': 'Our AI analyzes the purchase and shows 3 perfect complementary offers',
    'howItWorks.step2.details': 'Our intelligent matching system analyzes the purchased item, customer history, and your business rules to select the most relevant offers from your catalog and trusted partners. All in real-time.',
    'howItWorks.step3.title': 'Convert',
    'howItWorks.step3.desc': 'Customers add relevant items with 1-2 clicks, boosting your AOV instantly',
    'howItWorks.step3.details': 'Customers can add complementary products with a single click. Payment is processed instantly using their existing checkout session. No re-entering payment details required.',
    'howItWorks.metrics.title': 'Performance Metrics',
    'howItWorks.metrics.subtitle': 'See the impact AmplifAI can have on your business',
    'howItWorks.why.title': 'Why Merchants Choose AmplifAI',
    'howItWorks.faq.title': 'Frequently Asked Questions',
    'howItWorks.faq.subtitle': 'Everything you need to know about implementing AmplifAI',
    'howItWorks.cta.title': 'Ready to get started?',
    'howItWorks.cta.subtitle': 'Join the beta and start generating additional revenue from day one. Setup takes less than 10 minutes.',
    'howItWorks.cta.button': 'Talk to Us',

    // How It Works FAQ Items (EN)
    'howItWorks.faq.items.0.q': 'How does checkout integration work?',
    'howItWorks.faq.items.0.a': 'AmplifAI integrates seamlessly with your existing checkout flow. We support all major e-commerce platforms including Shopify, WooCommerce, Magento, and BigCommerce through lightweight snippets or native apps.',
    'howItWorks.faq.items.1.q': 'What happens with refunds?',
    'howItWorks.faq.items.1.a': 'Refunds are handled automatically. If the original item is refunded, any add-on purchases are also refunded proportionally.',
    'howItWorks.faq.items.2.q': 'How are partners vetted?',
    'howItWorks.faq.items.2.a': 'All partners go through KYC verification including business licenses, insurance, customer reviews, and financial standing.',
    'howItWorks.faq.items.3.q': 'Can I control what’s offered?',
    'howItWorks.faq.items.3.a': 'Yes. You have granular controls: allow/deny lists, category restrictions, and brand guidelines.',
    'howItWorks.faq.items.4.q': 'What analytics do I get?',
    'howItWorks.faq.items.4.a': 'A comprehensive dashboard shows attach rates, revenue per offer, partner performance, and customer satisfaction scores.',
    
    // About Page
    'about.title': 'About AmplifAI',
    'about.subtitle': 'We\'re revolutionizing post-purchase experiences with intelligent product recommendations',
    'about.mission.title': 'Our Mission',
    'about.mission.text': 'AmplifAI transforms the often-overlooked thank-you page into a powerful revenue generator. We believe that the moment after purchase is when customers are most receptive to complementary offers—and we\'ve built the technology to capitalize on that opportunity.',
    'about.story.title': 'Our Story',
    'about.story.text': 'Founded by e-commerce veterans who experienced the frustration of missed revenue opportunities firsthand, AmplifAI was born from a simple observation: customers who just made a purchase are in a buying mindset, but most retailers completely waste this golden moment.',
    'about.technology.title': 'Our Technology',
    'about.technology.text': 'Our proprietary AI analyzes purchase patterns, customer behavior, and product relationships to surface the most relevant add-on offers. We don\'t just show random products—we show the perfect complement to what was just purchased.',
    'about.team.title': 'Built by E-commerce Experts',
    'about.team.text': 'Our team combines deep e-commerce experience with cutting-edge AI expertise. We\'ve helped scale multiple online retailers and understand exactly what merchants need to succeed.',
    
    // Contact
    'contact.title': 'Join the Beta',
    'contact.subtitle': 'Ready to transform your thank-you page or join our partner network? Tell us about your business and let\'s get started.',
    'contact.merchant': 'I\'m a Webshop',
    'contact.partner': 'I\'m a Partner',
    'contact.name': 'Name',
    'contact.email': 'Work Email',
    'contact.company': 'Company',
    'contact.website': 'Website',
    'contact.platform': 'Platform',
    'contact.category': 'Category',
    'contact.submit': 'Count me in',
    'contact.success': 'Thanks! We\'ll reach out within 2 business days.',
    'contact.successTitle': 'Application submitted!',
    'contact.iam': 'I am a',
    'contact.merchantDesc': 'I sell products online',
    'contact.partnerDesc': 'I provide services',
    'contact.selectPlatform': 'Select your platform',
    'contact.selectCategory': 'Select your category',
    'contact.errorMsg': 'Please try again or contact us directly.',
    
    // Payment Modal
    'payment.title': 'Complete Your Purchase',
    'payment.subtitle': 'Choose your preferred payment method',
    'payment.card': 'Credit/Debit Card',
    'payment.paypal': 'PayPal',
    'payment.applepay': 'Apple Pay',
    'payment.googlepay': 'Google Pay',
    'payment.total': 'Total',
    'payment.confirm': 'Confirm Payment',
    'payment.processing': 'Processing...',
    'payment.success': 'Payment Successful!',
    'payment.successMsg': 'Your order has been confirmed. You will receive a confirmation email shortly.',
    'payment.cancel': 'Cancel',
    
    // Partner Modal
    'partner.bookAppointment': 'Book Your Appointment',
    'partner.availableTimes': 'Available times for',
    'partner.bookingBtn': 'Book Appointment',
    'partner.selectDateTime': 'Select Date & Time',
    'partner.addToCart': 'Add to Cart',
    'partner.appointmentBooked': 'Appointment Booked!',
    'partner.addedToCart': 'Added to Cart!',
    'partner.soldBy': 'Sold by Your Store',
    'partner.partnerBy': 'Partner:',
    'partner.reviews': 'reviews',
    'partner.your': 'Your',
    'partner.scheduledOn': 'is scheduled for',
    'partner.at': 'at',
    'partner.addedPrefix': 'has been added to your cart',
    
    // Footer
    'footer.company': 'Company',
    'footer.blog': 'Blog',
    'footer.careers': 'Careers',
    'footer.support': 'Support',
    'footer.help': 'Help Center',
    'footer.status': 'Status',
    'footer.legal': 'Legal',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.cookies': 'Cookie Policy',
    'footer.madeWithLove': 'Made with ❤️ for ambitious webshops',
    'footer.tagline': 'Turn your thank-you page into instant revenue with intelligent product recommendations.',

    // Categories
    'category.accessory': 'Accessory',
    'category.service': 'Service',
    'category.warranty': 'Warranty',
    'category.subscription': 'Subscription',
    'category.accessories': 'Accessories',
    'category.services': 'Services',
    'category.warranties': 'Warranties',
    'category.subscriptions': 'Subscriptions',

    // Common
    'common.by': 'by',
    'common.yourStore': 'Your Store',
    'common.submitting': 'Submitting...',
    'common.error': 'Something went wrong',

    // How It Works Features (EN)
    'howItWorks.features.fullBrand.title': 'Full Brand Control',
    'howItWorks.features.fullBrand.desc': 'Allow/deny lists, category controls, and brand safety to ensure only appropriate offers reach your customers.',
    'howItWorks.features.riskFree.title': 'Risk-Free Integration',
    'howItWorks.features.riskFree.desc': 'No upfront costs, no minimum commitments. Only pay when you generate additional revenue.',
    'howItWorks.features.realTime.title': 'Real-Time Analytics',
    'howItWorks.features.realTime.desc': 'Track performance, optimize offerings, and measure ROI with a comprehensive reporting dashboard.',

    // Example Products
    'products.tv': '4K Smart TV',
    'products.espresso': 'Espresso Machine',
    'products.bike': 'Road Bike',
    'products.washer': 'Washer & Dryer Set',
    'products.camera': 'Mirrorless Camera',
    'products.vacuum': 'Robot Vacuum',
    'products.laptop': 'Gaming Laptop',
    'products.mattress': 'Memory Foam Mattress',
    'products.grill': 'Outdoor Gas Grill',
    'products.headphones': 'Wireless Headphones',
    'products.smartwatch': 'Fitness Smartwatch',
    'products.airpurifier': 'HEPA Air Purifier',
    'products.standingdesk': 'Electric Standing Desk',
    'products.projector': '4K Home Theater Projector',

    // Example Offers
    'offers.professionalInstallation': 'Professional Installation',
    'offers.premiumHdmi': 'Premium HDMI Cable',
    'offers.extendedWarranty': 'Extended Warranty',
    'offers.descalerKit': 'Descaler Kit',
    'offers.baristaCourse': 'Barista Course',
    'offers.beanSubscription': 'Bean Subscription',
    'offers.bikeFitting': 'Professional Bike Fitting',
    'offers.gpsApp': 'GPS Training App',
    'offers.tuneup': 'Complete Tune-up',
    'offers.washerInstall': 'Professional Installation',
    'offers.stackingKit': 'Stacking Kit',
    'offers.washerWarranty': 'Extended Warranty',
    'offers.adobeSuite': 'Adobe Creative Suite',
    'offers.memoryCard': 'Memory Card Pro',
    'offers.photoWorkshop': 'Photography Workshop',
    'offers.vacuumWarranty': 'Extended Warranty',
    'offers.filterPack': 'Filter 3-Pack',
    'offers.cleaningService': 'Monthly Cleaning Service',
    'offers.gamingMouse': 'Gaming Mouse & Pad Set',
    'offers.cloudGaming': 'Cloud Gaming Subscription',
    'offers.pcSetup': 'Setup & Optimization',
    'offers.whiteGlove': 'White Glove Delivery',
    'offers.pillowSet': 'Pillow & Sheet Set',
    'offers.sleepTracker': 'Sleep Tracking Device',
    'offers.grillAssembly': 'Assembly & Setup',
    'offers.grillAccessories': 'Grilling Accessories Kit',
    'offers.bbqClass': 'BBQ Masterclass',
    'offers.carryingCase': 'Carrying Case Premium',
    'offers.headphoneWarranty': 'Extended Warranty',
    'offers.audioCalibration': 'Audio Calibration Service',
    'offers.sportBands': 'Sport Band Collection',
    'offers.healthCoach': 'Health Coach App Pro',
    'offers.personalTraining': 'Personal Training Session',
    'offers.filterReplacement': 'Replacement Filter 3-Pack',
    'offers.airQualityMonitor': 'Air Quality Monitor',
    'offers.airAssessment': 'Home Air Quality Assessment',
    'offers.ergoKit': 'Ergonomic Accessories Kit',
    'offers.deskAssembly': 'Professional Assembly',
    'offers.postureCoaching': 'Posture Coaching Session',
    'offers.projectorScreen': 'Projection Screen 120"',
    'offers.theaterInstall': 'Home Theater Installation',
    'offers.streamingBundle': 'Streaming Service Bundle',

    // Partner Names
    'partners.techInstallPro': 'TechInstall Pro',
    'partners.secureGuard': 'SecureGuard',
    'partners.coffeeMasters': 'Coffee Masters Academy',
    'partners.roastCo': 'Roast & Co',
    'partners.bikefitSpecialists': 'Bikefit Specialists',
    'partners.cycleTracker': 'CycleTracker Pro',
    'partners.precisionCycling': 'Precision Cycling',
    'partners.homeInstallExpress': 'HomeInstall Express',
    'partners.applianceCare': 'ApplianceCare Plus',
    'partners.adobe': 'Adobe',
    'partners.photoSkills': 'PhotoSkills Studio',
    'partners.roboGuard': 'RoboGuard',
    'partners.cleanPro': 'CleanPro Services',
    'partners.gameStream': 'GameStream Pro',
    'partners.pcPerformance': 'PC Performance Pro',
    'partners.comfortDelivery': 'Comfort Delivery Co',
    'partners.sleepTech': 'SleepTech Solutions',
    'partners.grillMasters': 'Grill Masters Assembly',
    'partners.pitmaster': 'Pitmaster Academy',
    'partners.audioGuard': 'AudioGuard Plus',
    'partners.soundTech': 'SoundTech Experts',
    'partners.fitLife': 'FitLife Pro',
    'partners.eliteFitness': 'Elite Fitness Coaches',
    'partners.cleanAir': 'CleanAir Tech',
    'partners.indoorEnv': 'Indoor Environment Pros',
    'partners.officeSetup': 'Office Setup Experts',
    'partners.ergoHealth': 'ErgoHealth Specialists',
    'partners.cinemaInstall': 'Cinema Install Pro',
    'partners.streamMax': 'StreamMax Entertainment',

    // Partner Descriptions
    'partnerDesc.techInstallPro': 'Professional TV mounting and setup service with 2-year warranty',
    'partnerDesc.secureGuard': '3-year comprehensive coverage including accidental damage',
    'partnerDesc.coffeeMasters': 'Learn professional espresso techniques in 2-hour hands-on session',
    'partnerDesc.roastCo': 'Premium single-origin beans delivered monthly',
    'partnerDesc.bikefitSpecialists': 'Comprehensive fitting session to optimize comfort and performance',
    'partnerDesc.cycleTracker': 'Advanced training plans and performance analytics',
    'partnerDesc.precisionCycling': 'Full inspection, adjustment, and maintenance service',
    'partnerDesc.homeInstallExpress': 'Full installation including plumbing and electrical connections',
    'partnerDesc.applianceCare': '5-year comprehensive coverage including parts and labor',
    'partnerDesc.adobe': 'Professional photo and video editing software suite',
    'partnerDesc.photoSkills': '4-hour intensive workshop covering composition and lighting',
    'partnerDesc.roboGuard': '2-year extended warranty covering all components',
    'partnerDesc.cleanPro': 'Professional house cleaning service complementing your robot vacuum',
    'partnerDesc.gameStream': 'Access 500+ AAA games without downloads',
    'partnerDesc.pcPerformance': 'Complete setup and performance optimization for gaming',
    'partnerDesc.comfortDelivery': 'Professional setup with old mattress removal',
    'partnerDesc.sleepTech': 'Advanced sleep analytics and improvement recommendations',
    'partnerDesc.grillMasters': 'Professional assembly with gas line connection and safety check',
    'partnerDesc.pitmaster': '3-hour hands-on class covering techniques and recipes',
    'partnerDesc.audioGuard': '3-year comprehensive coverage including accidental damage',
    'partnerDesc.soundTech': 'Professional hearing test and custom audio profile setup',
    'partnerDesc.fitLife': 'Personalized workout plans and nutrition tracking',
    'partnerDesc.eliteFitness': '1-on-1 fitness assessment and smartwatch optimization',
    'partnerDesc.cleanAir': 'Real-time PM2.5, VOC, and humidity monitoring with app',
    'partnerDesc.indoorEnv': 'Professional assessment with optimization recommendations',
    'partnerDesc.officeSetup': 'Complete assembly and ergonomic optimization',
    'partnerDesc.ergoHealth': 'Virtual consultation on optimal standing desk usage',
    'partnerDesc.cinemaInstall': 'Complete setup including mounting, wiring, and calibration',
    'partnerDesc.streamMax': 'Access to 4 premium streaming platforms with 4K content',
    'partnerDesc.yourStore': 'High-speed HDMI 2.1 cable supporting 4K@120Hz',

    // Partner Availability
    'partnerAvail.sameDayInstall': 'Same-day installation available',
    'partnerAvail.instantActivation': 'Instant activation',
    'partnerAvail.weekendSlots': 'Weekend slots available',
    'partnerAvail.startAnytime': 'Start anytime',
    'partnerAvail.book90min': 'Book your 90-minute session',
    'partnerAvail.freeTrial7': '7-day free trial',
    'partnerAvail.nextDay': 'Next-day service available',
    'partnerAvail.within3days': 'Schedule within 3 days',
    'partnerAvail.weekendWorkshops': 'Weekend workshops available',
    'partnerAvail.bookRecurring': 'Book recurring service',
    'partnerAvail.startImmediately': 'Start immediately',
    'partnerAvail.remoteSetup': 'Remote setup available',
    'partnerAvail.schedule2to4': 'Schedule 2-4 days ahead',
    'partnerAvail.ships1to2': 'Ships within 1-2 days',
    'partnerAvail.bookWithin48': 'Book within 48 hours',
    'partnerAvail.weekendClasses': 'Weekend classes available',
    'partnerAvail.remoteSession': 'Remote session available',
    'partnerAvail.freeTrial30': '30-day free trial',
    'partnerAvail.bookOnlineOrPerson': 'Book online or in-person',
    'partnerAvail.ships2to3': 'Ships within 2-3 days',
    'partnerAvail.within5days': 'Schedule within 5 days',
    'partnerAvail.sameDayService': 'Same-day service available',
    'partnerAvail.bookOnline': 'Book online sessions',
    'partnerAvail.book3to7': 'Book 3-7 days ahead',
    'partnerAvail.inStock': 'In stock',
    'partnerAvail.instantAccess': 'Instant access',

    // Success Stories
    'success.electronicsStore': 'Electronics Store',
    'success.electronicsQuote': 'Installation services have a 45% attach rate. Pure profit with zero inventory.',
    'success.electronicsMetric': 'Additional monthly revenue',
    'success.kitchenSpecialists': 'Kitchen Specialists',
    'success.kitchenQuote': 'Barista courses create loyal customers who buy more accessories.',
    'success.kitchenMetric': 'Average order value increase',
    'success.sportsRetailer': 'Sports Retailer',
    'success.sportsQuote': 'Professional fitting services became our highest margin offering.',
    'success.sportsMetric': 'Attach rate for services',

    // Not Found
    'notfound.title': 'Oops! Page not found',
    'notfound.back': 'Return to Home',

    // Merchants Page
    'merchants.hero.title': 'For <span class="gradient-text">Merchants</span>',
    'merchants.hero.subtitle': 'Turn your thank-you page into a revenue powerhouse. Add 15-40% to your average order value with zero operational overhead and complete brand control.',
    'merchants.hero.startTrial': 'Start Your Free Trial',
    'merchants.valueProps.title': 'Why Merchants Love AmplifAI',
    'merchants.valueProps.subtitle': 'Everything you need to generate additional revenue without additional work',
    'merchants.valueProps.foundMargin.title': 'Found Margin, Zero Extra Ops',
    'merchants.valueProps.foundMargin.desc': 'Generate additional revenue without inventory, shipping, or customer service overhead. Pure margin on every add-on sale.',
    'merchants.valueProps.brandSafe.title': 'Brand-Safe Controls',
    'merchants.valueProps.brandSafe.desc': 'Full control over partner offers with allow/deny lists, category restrictions, and brand guidelines. Maintain your reputation.',
    'merchants.valueProps.fastGoLive.title': '1-Day Go-Live, 7-Day ROI',
    'merchants.valueProps.fastGoLive.desc': 'Quick integration with immediate results. Most merchants see positive ROI within their first week of going live.',
    'merchants.valueProps.aiPowered.title': 'AI-Powered Optimization',
    'merchants.valueProps.aiPowered.desc': 'Our machine learning continuously improves offer relevance and timing to maximize conversion rates.',
    'merchants.valueProps.analytics.title': 'Comprehensive Analytics',
    'merchants.valueProps.analytics.desc': 'Real-time dashboard showing performance metrics, revenue attribution, and optimization opportunities.',
    'merchants.valueProps.integration.title': 'Seamless Integration',
    'merchants.valueProps.integration.desc': 'Works with all major e-commerce platforms. No disruption to your existing checkout flow or customer experience.',
    'merchants.results.title': 'Merchant Results',
    'merchants.results.subtitle': 'Real results from merchants using AmplifAI',
    'merchants.results.aovIncrease': 'Avg AOV Increase',
    'merchants.results.aovDesc': 'Typical lift after 30 days',
    'merchants.results.attachRate': 'Attach Rate',
    'merchants.results.attachDesc': 'Customers adding offers',
    'merchants.results.revenuePerOrder': 'Revenue Per Order',
    'merchants.results.revenueDesc': 'Additional earnings',
    'merchants.results.daysToROI': 'Days to ROI',
    'merchants.results.roiDesc': 'Break-even timeline',
    'merchants.integration.title': 'Getting Started Is Simple',
    'merchants.integration.subtitle': 'From setup to first sale in under 30 minutes',
    'merchants.integration.step1.title': 'Connect Your Store',
    'merchants.integration.step1.desc': 'Install our lightweight snippet or platform-specific app',
    'merchants.integration.step1.timeline': '5 minutes',
    'merchants.integration.step2.title': 'Configure Preferences',
    'merchants.integration.step2.desc': 'Set your brand guidelines and partner preferences',
    'merchants.integration.step2.timeline': '10 minutes',
    'merchants.integration.step3.title': 'Go Live',
    'merchants.integration.step3.desc': 'Start showing relevant offers to your customers',
    'merchants.integration.step3.timeline': 'Instant',
    'merchants.integration.step4.title': 'See Results',
    'merchants.integration.step4.desc': 'Monitor performance and optimize your strategy',
    'merchants.integration.step4.timeline': '7 days',
    'merchants.platforms.title': 'Works With Your Platform',
    'merchants.platforms.subtitle': 'Native integrations and universal compatibility',
    'merchants.platforms.merchants': 'merchants',
    'merchants.faq.title': 'Frequently Asked Questions',
    'merchants.faq.subtitle': 'Everything merchants need to know about AmplifAI',
    'merchants.faq.platforms.q': 'What e-commerce platforms do you support?',
    'merchants.faq.platforms.a': 'AmplifAI works with all major platforms including Shopify, WooCommerce, Magento, BigCommerce, Salesforce Commerce Cloud, and custom builds. We provide native integrations and universal JavaScript snippets.',
    'merchants.faq.refunds.q': 'How do refunds work?',
    'merchants.faq.refunds.a': 'Our refund coupling system automatically handles add-on refunds when the original item is returned. If customers return the main product, any related add-ons are refunded proportionally, maintaining complete transaction integrity.',
    'merchants.faq.control.q': 'What control do I have over partner offers?',
    'merchants.faq.control.a': 'Complete control. You can set category restrictions, maintain allow/deny lists for specific partners, require approval for new offers, and ensure all partner communications follow your brand guidelines.',
    'merchants.faq.vetting.q': 'How are partners vetted?',
    'merchants.faq.vetting.a': 'All partners go through our comprehensive KYC process including business license verification, insurance checks, customer review analysis, and financial standing assessment. Only high-quality, reliable partners are approved.',
    'merchants.faq.revenue.q': 'What\'s the revenue split?',
    'merchants.faq.revenue.a': 'You earn a commission on all partner sales generated through your customers, typically 10-25% depending on the service category. There are no upfront costs or monthly fees - you only pay when you earn.',
    'merchants.faq.design.q': 'Can I customize the widget design?',
    'merchants.faq.design.a': 'Yes, the widget is fully customizable to match your brand colors, fonts, and styling. We also offer A/B testing tools to optimize the design for maximum conversion.',
    'merchants.cta.title': 'Ready to boost your revenue?',
    'merchants.cta.subtitle': 'Join hundreds of merchants already generating additional revenue with AmplifAI. No setup costs, no risk, pure upside.',
    'merchants.cta.button': 'Talk to Us',

    // Partners Page
    'partners.hero.title': 'For <span class="gradient-text">Partners</span>',
    'partners.hero.subtitle': 'Reach new customers at the perfect moment - right after they\'ve made a purchase. Join our network and grow your business with high-intent, qualified leads.',
    'partners.hero.joinNetwork': 'Join Our Network',
    'partners.whyChoose.title': 'Why Partners Choose AmplifAI',
    'partners.whyChoose.subtitle': 'Join a marketplace that values quality and rewards great service',
    'partners.valueProp.zeroCac.title': 'Zero-CAC, High-Intent Moment',
    'partners.valueProp.zeroCac.desc': 'Reach customers at the perfect moment - right after they\'ve made a purchase and are in a buying mindset. No acquisition costs.',
    'partners.valueProp.fairDistribution.title': 'Fair Distribution Algorithm',
    'partners.valueProp.fairDistribution.desc': 'Our AI considers customer satisfaction scores and performance metrics to ensure quality partners get more visibility.',
    'partners.valueProp.weeklyPayouts.title': 'Weekly Payouts',
    'partners.valueProp.weeklyPayouts.desc': 'Get paid weekly for all completed services. No waiting months for your earnings. Transparent reporting and fast payments.',
    'partners.valueProp.qualifiedCustomers.title': 'Qualified Customer Base',
    'partners.valueProp.qualifiedCustomers.desc': 'Access customers from premium merchants who value quality and are willing to invest in complementary services.',
    'partners.valueProp.brandProtection.title': 'Brand Protection',
    'partners.valueProp.brandProtection.desc': 'We maintain high standards and provide clear \'offered by Partner\' labeling. Your reputation is protected by our vetting process.',
    'partners.valueProp.flexibleScheduling.title': 'Flexible Scheduling',
    'partners.valueProp.flexibleScheduling.desc': 'You control your capacity and availability. Our system matches customers to your schedule automatically.',
    'partners.successStory.title': 'Partner Success Story',
    'partners.successStory.subtitle': 'Real results from partners on our platform',
    'partners.successStory.name': 'InstallPro Services',
    'partners.successStory.category': 'Installation',
    'partners.successStory.partner': 'Partner',
    'partners.successStory.revenueGrowth': 'Revenue Growth',
    'partners.successStory.jobsCompleted': 'Jobs Completed',
    'partners.successStory.avgRating': 'Avg Rating',
    'partners.successStory.annualEarnings': 'Annual Earnings',
    'partners.successStory.quote': 'AmplifAI transformed our business. We went from hunting for customers to having a steady stream of high-quality jobs. The customers are already sold on the value - we just deliver great service.',
    'partners.successStory.author': 'Marcus Chen, Founder',
    'partners.categories.title': 'Partner Categories',
    'partners.categories.subtitle': 'Multiple ways to earn by providing value to customers',
    'partners.categories.installation.title': 'Installation Services',
    'partners.categories.installation.desc': 'Professional setup and installation for electronics, appliances, and equipment',
    'partners.categories.installation.example1': 'TV mounting',
    'partners.categories.installation.example2': 'Appliance installation',
    'partners.categories.installation.example3': 'Smart home setup',
    'partners.categories.installation.example4': 'Furniture assembly',
    'partners.categories.installation.demand': 'High',
    'partners.categories.installation.earning': '€80-€200 per job',
    'partners.categories.warranties.title': 'Extended Warranties',
    'partners.categories.warranties.desc': 'Protection plans and extended warranty coverage for purchased items',
    'partners.categories.warranties.example1': 'Electronics protection',
    'partners.categories.warranties.example2': 'Appliance warranties',
    'partners.categories.warranties.example3': 'Equipment coverage',
    'partners.categories.warranties.example4': 'Damage protection',
    'partners.categories.warranties.demand': 'Very High',
    'partners.categories.warranties.earning': '€25-€150 per policy',
    'partners.categories.subscriptions.title': 'Subscription Services',
    'partners.categories.subscriptions.desc': 'Recurring services and subscriptions that complement purchased products',
    'partners.categories.subscriptions.example1': 'Software subscriptions',
    'partners.categories.subscriptions.example2': 'Content streaming',
    'partners.categories.subscriptions.example3': 'Maintenance plans',
    'partners.categories.subscriptions.example4': 'Supply delivery',
    'partners.categories.subscriptions.demand': 'High',
    'partners.categories.subscriptions.earning': '€10-€50 monthly',
    'partners.categories.training.title': 'Training & Courses',
    'partners.categories.training.desc': 'Educational content and training programs related to purchased items',
    'partners.categories.training.example1': 'Photography workshops',
    'partners.categories.training.example2': 'Barista training',
    'partners.categories.training.example3': 'Fitness coaching',
    'partners.categories.training.example4': 'Tech tutorials',
    'partners.categories.training.demand': 'Medium',
    'partners.categories.training.earning': '€50-€300 per course',
    'partners.categories.accessories.title': 'Accessories & Add-ons',
    'partners.categories.accessories.desc': 'Complementary physical products that enhance the main purchase',
    'partners.categories.accessories.example1': 'Camera accessories',
    'partners.categories.accessories.example2': 'Kitchen tools',
    'partners.categories.accessories.example3': 'Bike equipment',
    'partners.categories.accessories.example4': 'Gaming peripherals',
    'partners.categories.accessories.demand': 'Very High',
    'partners.categories.accessories.earning': '€15-€100 per item',
    'partners.categories.maintenance.title': 'Maintenance & Support',
    'partners.categories.maintenance.desc': 'Ongoing maintenance, support, and repair services',
    'partners.categories.maintenance.example1': 'Device maintenance',
    'partners.categories.maintenance.example2': 'Cleaning services',
    'partners.categories.maintenance.example3': 'Tune-ups',
    'partners.categories.maintenance.example4': 'Technical support',
    'partners.categories.maintenance.demand': 'Medium',
    'partners.categories.maintenance.earning': '€40-€120 per service',
    'partners.categories.examples': 'Examples:',
    'partners.categories.demand': 'Demand:',
    'partners.metrics.title': 'Platform Metrics',
    'partners.metrics.subtitle': 'Join a growing network of successful partners',
    'partners.metrics.activePartners': 'Active Partners',
    'partners.metrics.acrossCategories': 'Across all categories',
    'partners.metrics.partnerSatisfaction': 'Partner Satisfaction',
    'partners.metrics.wouldRecommend': 'Would recommend us',
    'partners.metrics.avgRating': 'Avg Partner Rating',
    'partners.metrics.customerSatisfaction': 'Customer satisfaction',
    'partners.metrics.jobsCompleted': 'Jobs Completed',
    'partners.metrics.thisMonth': 'This month',
    'partners.requirements.title': 'Partner Requirements',
    'partners.requirements.subtitle': 'We maintain high standards to ensure the best experience for merchants and customers',
    'partners.requirements.1': 'Valid business license and insurance',
    'partners.requirements.2': 'Minimum 4.5-star customer rating',
    'partners.requirements.3': 'Proven track record in your category',
    'partners.requirements.4': 'Professional service delivery',
    'partners.requirements.5': 'Clear pricing and service descriptions',
    'partners.requirements.6': 'Commitment to AmplifAI quality standards',
    'partners.cta.title': 'Ready to grow your business?',
    'partners.cta.subtitle': 'Join AmplifAI\'s partner network and start accessing premium customers who are ready to purchase your services. No upfront costs, just results.',
    'partners.cta.button': 'Apply Now',
  },
  nl: {
    // Navigation
    'nav.home': 'Home',
    'nav.howItWorks': 'Hoe Het Werkt',
    'nav.examples': 'Voorbeelden',
    'nav.merchants': 'Voor Webshops',
    'nav.partners': 'Voor Partners',
    'nav.about': 'Over Ons',
'nav.contact': 'Contact',
'nav.joinBeta': 'Meld Je Aan',
    
// Home Page
    
    // Home Page
    'home.hero.title': 'Maak van je Bedankpagina Direct Omzet.',
    'home.hero.subtitle': 'AmplifAI toont zeer relevante add-ons uit je catalogus en vertrouwde partners—direct na de aankoop.',
    'home.hero.joinBeta': 'Meld Je Aan voor Beta',
'home.hero.seeExamples': 'Bekijk Voorbeelden',
'home.seeInAction': 'Zie het in actie',
'home.demo.subtitle': 'Zo transformeert je bedankpagina met AmplifAI',
'home.demo.hint': 'Tip: Dit voorbeeld is interactief — klik en probeer producten toe te voegen',
'home.results.title': 'Resultaten die voor zich spreken',
    'home.results.subtitle': 'Onze beta webshops zien al ongelooflijke resultaten met AmplifAI',
    'home.metrics.aov.label': 'Gemiddelde AOV Verhoging',
    'home.metrics.aov.desc': 'Typische stijging in gemiddelde bestelwaarde binnen 30 dagen',
    'home.metrics.extraRevenue.label': 'Extra Omzet',
    'home.metrics.extraRevenue.desc': 'Aanvullende omzet per voltooide bestelling',
    'home.metrics.attachRate.label': 'Bijkooppercentage',
    'home.metrics.attachRate.desc': 'Klanten die minstens één aanbieding toevoegen',
    'home.features.lightning.title': 'Bliksemnel',
    'home.features.lightning.desc': 'Verschijnt direct na aankoop. Geen vertraging, geen wrijving.',
    'home.features.ai.title': 'AI-Aangedreven Matching',
    'home.features.ai.desc': 'Slimme algoritmes vinden de perfecte complementaire producten.',
    'home.features.brand.title': 'Merkveilig',
    'home.features.brand.desc': 'Volledige controle over wat partners aan je klanten kunnen aanbieden.',
    'home.socialProof.title': 'Vertrouwd door toonaangevende e-commerce merken',
    'home.cta.title': 'Klaar om je bedankpagina te transformeren?',
    'home.cta.subtitle': 'Sluit je aan bij honderden webshops die al hun omzet verhogen met AmplifAI. Setup duurt minder dan 5 minuten.',
    'home.cta.button': 'Begin Vandaag Nog',
    
    // Widget Demo
'widget.title': 'Perfecte toevoegingen voor jou',
'widget.subtitle': 'Geselecteerd op basis van je aankoop',
'widget.orderConfirmed': 'Bestelling Bevestigd!',
'widget.thankYou': 'Bedankt voor je aankoop van de',
'widget.yourStore': 'Jouw Winkel',
'widget.partners': 'Partners',
'widget.addInOneClick': 'Toevoegen met 1 klik',
'widget.added': 'Toegevoegd!',
'widget.byAmplif': 'door AmplifAI',
'widget.sampleUrl': 'jouwwinkel.nl/bedankt',
    
    // Examples Page
    'examples.title': 'Perfecte Combinatie Voorbeelden',
    'examples.subtitle': 'Zie hoe AmplifAI perfecte productcombinaties creëert in verschillende categorieën. Elke combinatie is intelligent gekozen om de waarde voor je klanten te maximaliseren.',
    'examples.categories.title': 'Aanbod Categorieën',
    'examples.categories.subtitle': 'AmplifAI ondersteunt meerdere soorten complementaire aanbiedingen om je omzetpotentieel te maximaliseren',
    'examples.tryInDemo': 'Probeer in Demo',
    'examples.activePairings': 'Actieve Combinaties',
    'examples.examplePairingsTitle': 'Voorbeeld Combinaties',
    'examples.clickToSee': 'Klik om perfecte add-ons te zien',
    'examples.perfectAddons': 'Perfecte Add-ons',
    'examples.for': 'voor',
    'examples.successStories.title': 'Succesverhalen',
    'examples.successStories.subtitle': 'Echte resultaten van merchants die precies deze combinaties gebruiken',
    'examples.cta.title': 'Klaar om je eigen perfecte combinaties te maken?',
    'examples.cta.subtitle': 'Begin met onze bewezen combinatiesjablonen en pas ze aan voor je winkel. Ons team helpt je de beste kansen te identificeren.',
    'examples.cta.startBeta': 'Start Je Beta',
    'examples.cta.tryDemo': 'Probeer de Demo',
    'examples.grid.subtitle': 'Klik op een kaart om de perfecte complementaire aanbiedingen te zien. Elke combinatie is ontworpen om echte waarde toe te voegen voor je klanten.',
    
    // How It Works
    'howItWorks.title': 'Hoe AmplifAI Werkt',
    'howItWorks.subtitle': 'Transformeer je checkout-voltooiing in een omzetkans met maar 3 eenvoudige stappen',
    'howItWorks.step1.title': 'Installeren',
    'howItWorks.step1.desc': 'Voeg ons lichtgewicht snippet toe aan je bedankpagina in minder dan 5 minuten',
    'howItWorks.step1.details': 'Voeg onze lichtgewicht widget toe aan je bedankpagina met een eenvoudig code-snippet of installeer onze kant-en-klare extensies voor populaire platforms zoals Shopify, WooCommerce en BigCommerce. Duurt minder dan 5 minuten.',
    'howItWorks.step2.title': 'Matchen',
    'howItWorks.step2.desc': 'Onze AI analyseert de aankoop en toont 3 perfecte complementaire aanbiedingen',
    'howItWorks.step2.details': 'Ons intelligente matchingsysteem analyseert het gekochte artikel, klantgeschiedenis en je bedrijfsregels om de meest relevante aanbiedingen te selecteren uit je catalogus en vertrouwde partners. Alles in realtime.',
    'howItWorks.step3.title': 'Converteren',
    'howItWorks.step3.desc': 'Klanten voegen relevante items toe met 1-2 klikken, wat je AOV direct verhoogt',
    'howItWorks.step3.details': 'Klanten kunnen complementaire producten toevoegen met een enkele klik. Betaling wordt direct verwerkt via hun bestaande checkout-sessie. Geen hernieuw invoeren van betalingsgegevens vereist.',
    'howItWorks.metrics.title': 'Prestatie Indicatoren',
    'howItWorks.metrics.subtitle': 'Zie de impact die AmplifAI kan hebben op je bedrijf',
    'howItWorks.why.title': 'Waarom Merchants Kiezen voor AmplifAI',
    'howItWorks.faq.title': 'Veelgestelde Vragen',
    'howItWorks.faq.subtitle': 'Alles wat je moet weten over het implementeren van AmplifAI',
    'howItWorks.cta.title': 'Klaar om te beginnen?',
    'howItWorks.cta.subtitle': 'Meld je aan voor de beta en begin vanaf dag één extra omzet te genereren. Setup duurt minder dan 10 minuten.',
    'howItWorks.cta.button': 'Praat Met Ons',

    // How It Works FAQ Items (NL)
    'howItWorks.faq.items.0.q': 'Hoe werkt de checkout-integratie?',
    'howItWorks.faq.items.0.a': 'AmplifAI integreert naadloos met je bestaande checkout-flow. We ondersteunen alle grote e-commerce platforms (Shopify, WooCommerce, Magento, BigCommerce) via lichte snippets of native apps.',
    'howItWorks.faq.items.1.q': 'Wat gebeurt er bij restituties?',
    'howItWorks.faq.items.1.a': 'Restituties worden automatisch afgehandeld. Als het hoofdartikel wordt geretourneerd, worden add-on aankopen proportioneel terugbetaald.',
    'howItWorks.faq.items.2.q': 'Hoe worden partners gescreend?',
    'howItWorks.faq.items.2.a': 'Alle partners doorlopen KYC-verificatie inclusief bedrijfslicenties, verzekeringen, klantreviews en financiële beoordeling.',
    'howItWorks.faq.items.3.q': 'Kan ik bepalen wat er wordt aangeboden?',
    'howItWorks.faq.items.3.a': 'Ja. Je hebt fijne regie: toestaan/weigeren-lijsten, categorierestricties en merkrichtlijnen.',
    'howItWorks.faq.items.4.q': 'Welke analytics krijg ik?',
    'howItWorks.faq.items.4.a': 'Een uitgebreid dashboard toont bijkooppercentages, omzet per aanbieding, partnerprestaties en klanttevredenheidsscores.',
    
    // About Page
    'about.title': 'Over AmplifAI',
    'about.subtitle': 'Wij revolutioneren na-aankoop ervaringen met intelligente productaanbevelingen',
    'about.mission.title': 'Onze Missie',
    'about.mission.text': 'AmplifAI transformeert de vaak over het hoofd geziene bedankpagina in een krachtige omzetgenerator. Wij geloven dat het moment na de aankoop is wanneer klanten het meest ontvankelijk zijn voor complementaire aanbiedingen—en wij hebben de technologie gebouwd om van die kans gebruik te maken.',
    'about.story.title': 'Ons Verhaal',
    'about.story.text': 'Opgericht door e-commerce veteranen die de frustratie van gemiste omzetkansen aan den lijve hebben ondervonden, werd AmplifAI geboren uit een eenvoudige observatie: klanten die net een aankoop hebben gedaan bevinden zich in een koopmentaliteit, maar de meeste retailers verspillen dit gouden moment volledig.',
    'about.technology.title': 'Onze Technologie',
    'about.technology.text': 'Onze eigenlijke AI analyseert aankooppatronen, klantgedrag en productrelaties om de meest relevante add-on aanbiedingen naar boven te brengen. We tonen niet zomaar willekeurige producten—we tonen de perfecte aanvulling op wat net is gekocht.',
    'about.team.title': 'Gebouwd door E-commerce Experts',
    'about.team.text': 'Ons team combineert diepe e-commerce ervaring met geavanceerde AI-expertise. We hebben meerdere online retailers geholpen schalen en begrijpen precies wat webshops nodig hebben om te slagen.',
    
    // Contact
'contact.title': 'Meld Je Aan',
'contact.subtitle': 'Klaar om je bedankpagina te transformeren of je aan te sluiten bij ons partnernetwerk? Vertel ons over je bedrijf en laten we beginnen.',
'contact.merchant': 'Ik ben een Webshop',
'contact.partner': 'Ik ben een Partner',
'contact.name': 'Naam',
'contact.email': 'Werk E-mail',
'contact.company': 'Bedrijf',
'contact.website': 'Website',
'contact.platform': 'Platform',
'contact.category': 'Categorie',
'contact.submit': 'Schrijf me in',
'contact.success': 'Bedankt! We nemen binnen 2 werkdagen contact op.',
'contact.successTitle': 'Aanmelding ingediend!',
'contact.iam': 'Ik ben een',
'contact.merchantDesc': 'Ik verkoop producten online',
'contact.partnerDesc': 'Ik bied diensten aan',
'contact.selectPlatform': 'Selecteer je platform',
'contact.selectCategory': 'Selecteer je categorie',
'contact.errorMsg': 'Probeer het opnieuw of neem direct contact met ons op.',
    
    // Payment Modal
    'payment.title': 'Voltooi Je Aankoop',
    'payment.subtitle': 'Kies je voorkeursbetaalmethode',
    'payment.card': 'Credit/Debit Card',
    'payment.paypal': 'PayPal',
    'payment.applepay': 'Apple Pay',
    'payment.googlepay': 'Google Pay',
    'payment.total': 'Totaal',
    'payment.confirm': 'Bevestig Betaling',
    'payment.processing': 'Verwerken...',
    'payment.success': 'Betaling Succesvol!',
    'payment.successMsg': 'Je bestelling is bevestigd. Je ontvangt binnenkort een bevestigingsmail.',
    'payment.cancel': 'Annuleren',
    
    // Partner Modal
'partner.bookAppointment': 'Boek Je Afspraak',
'partner.availableTimes': 'Beschikbare tijden voor',
'partner.bookingBtn': 'Boek Afspraak',
'partner.selectDateTime': 'Selecteer Datum & Tijd',
'partner.addToCart': 'Toevoegen aan Winkelwagen',
'partner.appointmentBooked': 'Afspraak Geboekt!',
'partner.addedToCart': 'Toegevoegd aan Winkelwagen!',
'partner.soldBy': 'Verkocht door Jouw Winkel',
'partner.partnerBy': 'Partner:',
'partner.reviews': 'beoordelingen',
'partner.your': 'Je',
'partner.scheduledOn': 'is gepland op',
'partner.at': 'om',
'partner.addedPrefix': 'is toegevoegd aan je winkelwagen',

// Footer
'footer.company': 'Bedrijf',
'footer.company': 'Bedrijf',
'footer.blog': 'Blog',
'footer.careers': 'Vacatures',
'footer.support': 'Ondersteuning',
'footer.help': 'Helpcentrum',
'footer.status': 'Status',
'footer.legal': 'Juridisch',
'footer.privacy': 'Privacybeleid',
'footer.terms': 'Servicevoorwaarden',
'footer.cookies': 'Cookiebeleid',
'footer.madeWithLove': 'Gemaakt met ❤️ voor ambitieuze webshops',
'footer.tagline': 'Transformeer je bedankpagina in directe omzet met intelligente productaanbevelingen.',
'footer.copyright': '© 2024 AmplifAI. Alle rechten voorbehouden.',

    // Categories
    'category.accessory': 'Accessoire',
    'category.service': 'Service',
    'category.warranty': 'Garantie',
    'category.subscription': 'Abonnement',
    'category.accessories': 'Accessoires',
    'category.services': 'Services',
    'category.warranties': 'Garanties',
    'category.subscriptions': 'Abonnementen',

    // Common
    'common.by': 'door',
    'common.yourStore': 'Jouw Winkel',
    'common.submitting': 'Versturen...',
    'common.error': 'Er ging iets mis',

    // How It Works Features (NL)
    'howItWorks.features.fullBrand.title': 'Volledige Merkonthechting',
    'howItWorks.features.fullBrand.desc': 'Toestaan/weigeren-lijsten, categoriebeheer en merkveiligheid zorgen dat alleen passende aanbiedingen getoond worden.',
    'howItWorks.features.riskFree.title': 'Risicovrije Integratie',
    'howItWorks.features.riskFree.desc': 'Geen opstartkosten, geen minimale verplichtingen. Je betaalt alleen bij extra omzet.',
    'howItWorks.features.realTime.title': 'Realtime Analytics',
    'howItWorks.features.realTime.desc': 'Volg prestaties, optimaliseer aanbiedingen en meet ROI met een uitgebreid rapportagedashboard.',

    // Example Products
    'products.tv': '4K Smart TV',
    'products.espresso': 'Espresso Machine',
    'products.bike': 'Racefiets',
    'products.washer': 'Wasmachine & Droger Set',
    'products.camera': 'Systeemcamera',
    'products.vacuum': 'Robot Stofzuiger',
    'products.laptop': 'Gaming Laptop',
    'products.mattress': 'Memory Foam Matras',
    'products.grill': 'Gasbarbecue Buiten',
    'products.headphones': 'Draadloze Koptelefoon',
    'products.smartwatch': 'Fitness Smartwatch',
    'products.airpurifier': 'HEPA Luchtreiniger',
    'products.standingdesk': 'Elektrisch Sta-Bureau',
    'products.projector': '4K Thuisbioscoop Projector',

    // Example Offers
    'offers.professionalInstallation': 'Professionele Installatie',
    'offers.premiumHdmi': 'Premium HDMI Kabel',
    'offers.extendedWarranty': 'Verlengde Garantie',
    'offers.descalerKit': 'Ontkalkingskit',
    'offers.baristaCourse': 'Barista Cursus',
    'offers.beanSubscription': 'Bonen Abonnement',
    'offers.bikeFitting': 'Professionele Fietsafstelling',
    'offers.gpsApp': 'GPS Trainings App',
    'offers.tuneup': 'Volledige Onderhoudsbeurt',
    'offers.washerInstall': 'Professionele Installatie',
    'offers.stackingKit': 'Stapelkit',
    'offers.washerWarranty': 'Verlengde Garantie',
    'offers.adobeSuite': 'Adobe Creative Suite',
    'offers.memoryCard': 'Geheugenkaart Pro',
    'offers.photoWorkshop': 'Fotografie Workshop',
    'offers.vacuumWarranty': 'Verlengde Garantie',
    'offers.filterPack': 'Filter 3-Pack',
    'offers.cleaningService': 'Maandelijkse Schoonmaakservice',
    'offers.gamingMouse': 'Gaming Muis & Mousepad Set',
    'offers.cloudGaming': 'Cloud Gaming Abonnement',
    'offers.pcSetup': 'Setup & Optimalisatie',
    'offers.whiteGlove': 'White Glove Bezorging',
    'offers.pillowSet': 'Kussen & Lakens Set',
    'offers.sleepTracker': 'Slaap Tracking Apparaat',
    'offers.grillAssembly': 'Montage & Setup',
    'offers.grillAccessories': 'Barbecue Accessoires Kit',
    'offers.bbqClass': 'BBQ Masterclass',
    'offers.carryingCase': 'Premium Draagtas',
    'offers.headphoneWarranty': 'Verlengde Garantie',
    'offers.audioCalibration': 'Audio Calibratie Service',
    'offers.sportBands': 'Sport Band Collectie',
    'offers.healthCoach': 'Gezondheidscoach App Pro',
    'offers.personalTraining': 'Persoonlijke Trainings Sessie',
    'offers.filterReplacement': 'Vervangende Filter 3-Pack',
    'offers.airQualityMonitor': 'Luchtkwaliteit Monitor',
    'offers.airAssessment': 'Luchtkwaliteit Beoordeling Thuis',
    'offers.ergoKit': 'Ergonomische Accessoires Kit',
    'offers.deskAssembly': 'Professionele Montage',
    'offers.postureCoaching': 'Houdings Coaching Sessie',
    'offers.projectorScreen': 'Projectiescherm 120"',
    'offers.theaterInstall': 'Thuisbioscoop Installatie',
    'offers.streamingBundle': 'Streaming Service Bundel',

    // Partner Names
    'partners.techInstallPro': 'TechInstall Pro',
    'partners.secureGuard': 'SecureGuard',
    'partners.coffeeMasters': 'Coffee Masters Academie',
    'partners.roastCo': 'Roast & Co',
    'partners.bikefitSpecialists': 'Fietsfit Specialisten',
    'partners.cycleTracker': 'FietsTracker Pro',
    'partners.precisionCycling': 'Precision Fietsen',
    'partners.homeInstallExpress': 'ThuisInstallatie Express',
    'partners.applianceCare': 'Apparaat Zorg Plus',
    'partners.adobe': 'Adobe',
    'partners.photoSkills': 'FotoVaardigheden Studio',
    'partners.roboGuard': 'RobotBescherming',
    'partners.cleanPro': 'SchoonPro Services',
    'partners.gameStream': 'GameStream Pro',
    'partners.pcPerformance': 'PC Prestatie Pro',
    'partners.comfortDelivery': 'Comfort Bezorg Bedrijf',
    'partners.sleepTech': 'SlaapTech Oplossingen',
    'partners.grillMasters': 'Grill Masters Montage',
    'partners.pitmaster': 'Pitmaster Academie',
    'partners.audioGuard': 'AudioBescherming Plus',
    'partners.soundTech': 'GeluidTech Experts',
    'partners.fitLife': 'FitLife Pro',
    'partners.eliteFitness': 'Elite Fitness Coaches',
    'partners.cleanAir': 'SchoneluchtTech',
    'partners.indoorEnv': 'Binnenklimaat Professionals',
    'partners.officeSetup': 'Kantoor Setup Experts',
    'partners.ergoHealth': 'ErgoGezondheid Specialisten',
    'partners.cinemaInstall': 'Cinema Installatie Pro',
    'partners.streamMax': 'StreamMax Entertainment',

    // Partner Descriptions
    'partnerDesc.techInstallPro': 'Professionele TV montage en setup service met 2 jaar garantie',
    'partnerDesc.secureGuard': '3 jaar uitgebreide dekking inclusief accidentele schade',
    'partnerDesc.coffeeMasters': 'Leer professionele espresso technieken in 2 uur hands-on sessie',
    'partnerDesc.roastCo': 'Premium single-origin bonen maandelijks geleverd',
    'partnerDesc.bikefitSpecialists': 'Uitgebreide afstelling sessie om comfort en prestaties te optimaliseren',
    'partnerDesc.cycleTracker': 'Geavanceerde trainingsplannen en prestatie analyses',
    'partnerDesc.precisionCycling': 'Volledige inspectie, afstelling en onderhoudsservice',
    'partnerDesc.homeInstallExpress': 'Volledige installatie inclusief loodgieters- en elektrische aansluitingen',
    'partnerDesc.applianceCare': '5 jaar uitgebreide dekking inclusief onderdelen en arbeid',
    'partnerDesc.adobe': 'Professionele foto en video bewerkingssoftware suite',
    'partnerDesc.photoSkills': '4 uur intensieve workshop over compositie en belichting',
    'partnerDesc.roboGuard': '2 jaar verlengde garantie voor alle componenten',
    'partnerDesc.cleanPro': 'Professionele schoonmaakservice als aanvulling op je robot stofzuiger',
    'partnerDesc.gameStream': 'Toegang tot 500+ AAA games zonder downloads',
    'partnerDesc.pcPerformance': 'Volledige setup en prestatie optimalisatie voor gaming',
    'partnerDesc.comfortDelivery': 'Professionele setup met oude matras verwijdering',
    'partnerDesc.sleepTech': 'Geavanceerde slaapanalyses en verbeteraanbevelingen',
    'partnerDesc.grillMasters': 'Professionele montage met gasleiding aansluiting en veiligheidscontrole',
    'partnerDesc.pitmaster': '3 uur hands-on les over technieken en recepten',
    'partnerDesc.audioGuard': '3 jaar uitgebreide dekking inclusief accidentele schade',
    'partnerDesc.soundTech': 'Professionele gehoortest en aangepast audioprofiel setup',
    'partnerDesc.fitLife': 'Gepersonaliseerde trainingsplannen en voedingstracking',
    'partnerDesc.eliteFitness': '1-op-1 fitness beoordeling en smartwatch optimalisatie',
    'partnerDesc.cleanAir': 'Real-time PM2.5, VOC en luchtvochtigheid monitoring met app',
    'partnerDesc.indoorEnv': 'Professionele beoordeling met optimalisatie aanbevelingen',
    'partnerDesc.officeSetup': 'Volledige montage en ergonomische optimalisatie',
    'partnerDesc.ergoHealth': 'Virtueel consult over optimaal sta-bureau gebruik',
    'partnerDesc.cinemaInstall': 'Volledige setup inclusief montage, bedrading en kalibratie',
    'partnerDesc.streamMax': 'Toegang tot 4 premium streamingplatforms met 4K content',
    'partnerDesc.yourStore': 'Snelle HDMI 2.1 kabel met ondersteuning voor 4K@120Hz',

    // Partner Availability
    'partnerAvail.sameDayInstall': 'Installatie op dezelfde dag beschikbaar',
    'partnerAvail.instantActivation': 'Directe activering',
    'partnerAvail.weekendSlots': 'Weekendslots beschikbaar',
    'partnerAvail.startAnytime': 'Start wanneer je wilt',
    'partnerAvail.book90min': 'Boek je 90-minuten sessie',
    'partnerAvail.freeTrial7': '7 dagen gratis proefperiode',
    'partnerAvail.nextDay': 'Service volgende dag beschikbaar',
    'partnerAvail.within3days': 'Plannen binnen 3 dagen',
    'partnerAvail.weekendWorkshops': 'Weekend workshops beschikbaar',
    'partnerAvail.bookRecurring': 'Boek terugkerende service',
    'partnerAvail.startImmediately': 'Direct starten',
    'partnerAvail.remoteSetup': 'Setup op afstand beschikbaar',
    'partnerAvail.schedule2to4': 'Plannen 2-4 dagen vooruit',
    'partnerAvail.ships1to2': 'Verzending binnen 1-2 dagen',
    'partnerAvail.bookWithin48': 'Boeken binnen 48 uur',
    'partnerAvail.weekendClasses': 'Weekend lessen beschikbaar',
    'partnerAvail.remoteSession': 'Sessie op afstand beschikbaar',
    'partnerAvail.freeTrial30': '30 dagen gratis proefperiode',
    'partnerAvail.bookOnlineOrPerson': 'Boek online of persoonlijk',
    'partnerAvail.ships2to3': 'Verzending binnen 2-3 dagen',
    'partnerAvail.within5days': 'Plannen binnen 5 dagen',
    'partnerAvail.sameDayService': 'Service op dezelfde dag beschikbaar',
    'partnerAvail.bookOnline': 'Boek online sessies',
    'partnerAvail.book3to7': 'Boeken 3-7 dagen vooruit',
    'partnerAvail.inStock': 'Op voorraad',
    'partnerAvail.instantAccess': 'Directe toegang',

    // Success Stories
    'success.electronicsStore': 'Electronica Winkel',
    'success.electronicsQuote': 'Installatieservices hebben een 45% bijkooppercentage. Pure winst met nul voorraad.',
    'success.electronicsMetric': 'Extra maandelijkse omzet',
    'success.kitchenSpecialists': 'Keuken Specialisten',
    'success.kitchenQuote': 'Barista cursussen creëren loyale klanten die meer accessoires kopen.',
    'success.kitchenMetric': 'Gemiddelde bestelwaarde verhoging',
    'success.sportsRetailer': 'Sport Retailer',
    'success.sportsQuote': 'Professionele afstelling services werden ons hoogste marge aanbod.',
    'success.sportsMetric': 'Bijkooppercentage voor services',

    // Not Found
'notfound.title': 'Oeps! Pagina niet gevonden',
'notfound.back': 'Terug naar Home',

// Index Page
'index.welcomeTitle': 'Welkom bij je lege app',
'index.welcomeSubtitle': 'Begin hier met het bouwen van je geweldige project!',

// Merchants Page
'merchants.hero.title': 'Voor <span class="gradient-text">Webshops</span>',
'merchants.hero.subtitle': 'Transformeer je bedankpagina in een omzet krachtpatser. Voeg 15-40% toe aan je gemiddelde bestelwaarde met nul operationele overhead en volledige merkcontrole.',
'merchants.hero.startTrial': 'Start Je Gratis Proefperiode',
'merchants.valueProps.title': 'Waarom Webshops Dol Zijn op AmplifAI',
'merchants.valueProps.subtitle': 'Alles wat je nodig hebt om extra omzet te genereren zonder extra werk',
'merchants.valueProps.foundMargin.title': 'Gevonden Marge, Nul Extra Ops',
'merchants.valueProps.foundMargin.desc': 'Genereer extra omzet zonder voorraad, verzending of klantenservice overhead. Pure marge op elke add-on verkoop.',
'merchants.valueProps.brandSafe.title': 'Merkveilige Controles',
'merchants.valueProps.brandSafe.desc': 'Volledige controle over partneraanbiedingen met toestaan/weigeren lijsten, categorierestricties en merkrichtlijnen. Behoud je reputatie.',
'merchants.valueProps.fastGoLive.title': '1-Dag Go-Live, 7-Dag ROI',
'merchants.valueProps.fastGoLive.desc': 'Snelle integratie met directe resultaten. De meeste webshops zien positieve ROI binnen hun eerste week live.',
'merchants.valueProps.aiPowered.title': 'AI-Aangedreven Optimalisatie',
'merchants.valueProps.aiPowered.desc': 'Onze machine learning verbetert continu aanbiedingrelevantie en timing om conversiepercentages te maximaliseren.',
'merchants.valueProps.analytics.title': 'Uitgebreide Analytics',
'merchants.valueProps.analytics.desc': 'Realtime dashboard met prestatie-indicatoren, omzet-attributie en optimalisatiekansen.',
'merchants.valueProps.integration.title': 'Naadloze Integratie',
'merchants.valueProps.integration.desc': 'Werkt met alle grote e-commerce platforms. Geen verstoring van je bestaande checkout-flow of klantervaring.',
'merchants.results.title': 'Webshop Resultaten',
'merchants.results.subtitle': 'Echte resultaten van webshops die AmplifAI gebruiken',
'merchants.results.aovIncrease': 'Gem AOV Verhoging',
'merchants.results.aovDesc': 'Typische stijging na 30 dagen',
'merchants.results.attachRate': 'Bijkooppercentage',
'merchants.results.attachDesc': 'Klanten die aanbiedingen toevoegen',
'merchants.results.revenuePerOrder': 'Omzet Per Bestelling',
'merchants.results.revenueDesc': 'Extra verdiensten',
'merchants.results.daysToROI': 'Dagen Tot ROI',
'merchants.results.roiDesc': 'Break-even tijdlijn',
'merchants.integration.title': 'Beginnen Is Eenvoudig',
'merchants.integration.subtitle': 'Van setup tot eerste verkoop in minder dan 30 minuten',
'merchants.integration.step1.title': 'Verbind Je Winkel',
'merchants.integration.step1.desc': 'Installeer ons lichtgewicht snippet of platform-specifieke app',
'merchants.integration.step1.timeline': '5 minuten',
'merchants.integration.step2.title': 'Configureer Voorkeuren',
'merchants.integration.step2.desc': 'Stel je merkrichtlijnen en partnervoorkeuren in',
'merchants.integration.step2.timeline': '10 minuten',
'merchants.integration.step3.title': 'Ga Live',
'merchants.integration.step3.desc': 'Begin relevante aanbiedingen te tonen aan je klanten',
'merchants.integration.step3.timeline': 'Direct',
'merchants.integration.step4.title': 'Zie Resultaten',
'merchants.integration.step4.desc': 'Bewaak prestaties en optimaliseer je strategie',
'merchants.integration.step4.timeline': '7 dagen',
'merchants.platforms.title': 'Werkt Met Je Platform',
'merchants.platforms.subtitle': 'Native integraties en universele compatibiliteit',
'merchants.platforms.merchants': 'webshops',
'merchants.faq.title': 'Veelgestelde Vragen',
'merchants.faq.subtitle': 'Alles wat webshops moeten weten over AmplifAI',
'merchants.faq.platforms.q': 'Welke e-commerce platforms ondersteunen jullie?',
'merchants.faq.platforms.a': 'AmplifAI werkt met alle grote platforms waaronder Shopify, WooCommerce, Magento, BigCommerce, Salesforce Commerce Cloud en aangepaste builds. We bieden native integraties en universele JavaScript snippets.',
'merchants.faq.refunds.q': 'Hoe werken restituties?',
'merchants.faq.refunds.a': 'Ons restitutiekoppelingssysteem handelt automatisch add-on restituties af wanneer het oorspronkelijke artikel wordt geretourneerd. Als klanten het hoofdproduct retourneren, worden gerelateerde add-ons proportioneel gerestitueerd, waarbij volledige transactie-integriteit behouden blijft.',
'merchants.faq.control.q': 'Welke controle heb ik over partneraanbiedingen?',
'merchants.faq.control.a': 'Volledige controle. Je kunt categorierestricties instellen, toestaan/weigeren lijsten onderhouden voor specifieke partners, goedkeuring vereisen voor nieuwe aanbiedingen, en ervoor zorgen dat alle partnercommunicatie je merkrichtlijnen volgt.',
'merchants.faq.vetting.q': 'Hoe worden partners gescreend?',
'merchants.faq.vetting.a': 'Alle partners doorlopen ons uitgebreide KYC-proces inclusief verificatie van bedrijfslicenties, verzekeringscontroles, analyse van klantrecensies en beoordeling van financiële status. Alleen hoogkwaliteit, betrouwbare partners worden goedgekeurd.',
'merchants.faq.revenue.q': 'Wat is de omzetverdeling?',
'merchants.faq.revenue.a': 'Je verdient een commissie op alle partnerverkopen gegenereerd via je klanten, doorgaans 10-25% afhankelijk van de dienstcategorie. Er zijn geen upfront kosten of maandelijkse vergoedingen - je betaalt alleen wanneer je verdient.',
'merchants.faq.design.q': 'Kan ik het widget ontwerp aanpassen?',
'merchants.faq.design.a': 'Ja, de widget is volledig aanpasbaar aan je merkkleuren, lettertypen en styling. We bieden ook A/B-testtools om het ontwerp te optimaliseren voor maximale conversie.',
'merchants.cta.title': 'Klaar om je omzet te verhogen?',
'merchants.cta.subtitle': 'Sluit je aan bij honderden webshops die al extra omzet genereren met AmplifAI. Geen setup kosten, geen risico, puur voordeel.',
'merchants.cta.button': 'Praat Met Ons',

    // Partners Page
    'partners.hero.title': 'Voor <span class="gradient-text">Partners</span>',
    'partners.hero.subtitle': 'Bereik nieuwe klanten op het perfecte moment - direct nadat ze een aankoop hebben gedaan. Sluit je aan bij ons netwerk en laat je bedrijf groeien met hoogkwalificeerde, geïnteresseerde leads.',
    'partners.hero.joinNetwork': 'Meld Je Aan Bij Ons Netwerk',
    'partners.whyChoose.title': 'Waarom Partners Kiezen voor AmplifAI',
    'partners.whyChoose.subtitle': 'Sluit je aan bij een marktplaats die kwaliteit waardeert en geweldige service beloont',
    'partners.valueProp.zeroCac.title': 'Zero-CAC, Hoog-Intent Moment',
    'partners.valueProp.zeroCac.desc': 'Bereik klanten op het perfecte moment - direct nadat ze een aankoop hebben gedaan en zich in een koopmentaliteit bevinden. Geen acquisitiekosten.',
    'partners.valueProp.fairDistribution.title': 'Eerlijk Distributie Algoritme',
    'partners.valueProp.fairDistribution.desc': 'Onze AI houdt rekening met klanttevredenheidsscores en prestatiemetrics om ervoor te zorgen dat kwaliteitspartners meer zichtbaarheid krijgen.',
    'partners.valueProp.weeklyPayouts.title': 'Wekelijkse Uitbetalingen',
    'partners.valueProp.weeklyPayouts.desc': 'Word wekelijks uitbetaald voor alle voltooide diensten. Geen maanden wachten op je inkomsten. Transparante rapportage en snelle betalingen.',
    'partners.valueProp.qualifiedCustomers.title': 'Gekwalificeerd Klantenbestand',
    'partners.valueProp.qualifiedCustomers.desc': 'Toegang tot klanten van premium merchants die waarde hechten aan kwaliteit en bereid zijn te investeren in complementaire diensten.',
    'partners.valueProp.brandProtection.title': 'Merkbescherming',
    'partners.valueProp.brandProtection.desc': 'We handhaven hoge standaarden en bieden duidelijke \'aangeboden door Partner\' labeling. Je reputatie wordt beschermd door ons selectieproces.',
    'partners.valueProp.flexibleScheduling.title': 'Flexibel Plannen',
    'partners.valueProp.flexibleScheduling.desc': 'Jij bepaalt je capaciteit en beschikbaarheid. Ons systeem matcht klanten automatisch aan je schema.',
    'partners.successStory.title': 'Partner Succesverhaal',
    'partners.successStory.subtitle': 'Echte resultaten van partners op ons platform',
    'partners.successStory.name': 'InstallPro Services',
    'partners.successStory.category': 'Installatie',
    'partners.successStory.partner': 'Partner',
    'partners.successStory.revenueGrowth': 'Omzetgroei',
    'partners.successStory.jobsCompleted': 'Voltooide Klussen',
    'partners.successStory.avgRating': 'Gem. Beoordeling',
    'partners.successStory.annualEarnings': 'Jaarlijkse Inkomsten',
    'partners.successStory.quote': 'AmplifAI heeft ons bedrijf getransformeerd. We gingen van het jagen op klanten naar een gestage stroom van hoogwaardige klussen. De klanten zijn al overtuigd van de waarde - wij leveren gewoon geweldige service.',
    'partners.successStory.author': 'Marcus Chen, Oprichter',
    'partners.categories.title': 'Partner Categorieën',
    'partners.categories.subtitle': 'Meerdere manieren om te verdienen door waarde te bieden aan klanten',
    'partners.categories.installation.title': 'Installatie Services',
    'partners.categories.installation.desc': 'Professionele setup en installatie voor elektronica, apparaten en uitrusting',
    'partners.categories.installation.example1': 'TV montage',
    'partners.categories.installation.example2': 'Apparaat installatie',
    'partners.categories.installation.example3': 'Smart home setup',
    'partners.categories.installation.example4': 'Meubelassemblage',
    'partners.categories.installation.demand': 'Hoog',
    'partners.categories.installation.earning': '€80-€200 per klus',
    'partners.categories.warranties.title': 'Verlengde Garanties',
    'partners.categories.warranties.desc': 'Beschermingsplannen en verlengde garantiedekking voor gekochte artikelen',
    'partners.categories.warranties.example1': 'Elektronica bescherming',
    'partners.categories.warranties.example2': 'Apparaat garanties',
    'partners.categories.warranties.example3': 'Uitrusting dekking',
    'partners.categories.warranties.example4': 'Schadebescherming',
    'partners.categories.warranties.demand': 'Zeer Hoog',
    'partners.categories.warranties.earning': '€25-€150 per polis',
    'partners.categories.subscriptions.title': 'Abonnement Services',
    'partners.categories.subscriptions.desc': 'Terugkerende services en abonnementen die gekochte producten aanvullen',
    'partners.categories.subscriptions.example1': 'Software abonnementen',
    'partners.categories.subscriptions.example2': 'Content streaming',
    'partners.categories.subscriptions.example3': 'Onderhoudsplannen',
    'partners.categories.subscriptions.example4': 'Bevoorradingslevering',
    'partners.categories.subscriptions.demand': 'Hoog',
    'partners.categories.subscriptions.earning': '€10-€50 per maand',
    'partners.categories.training.title': 'Training & Cursussen',
    'partners.categories.training.desc': 'Educatieve content en trainingsprogramma\'s gerelateerd aan gekochte artikelen',
    'partners.categories.training.example1': 'Fotografie workshops',
    'partners.categories.training.example2': 'Barista training',
    'partners.categories.training.example3': 'Fitness coaching',
    'partners.categories.training.example4': 'Tech tutorials',
    'partners.categories.training.demand': 'Gemiddeld',
    'partners.categories.training.earning': '€50-€300 per cursus',
    'partners.categories.accessories.title': 'Accessoires & Add-ons',
    'partners.categories.accessories.desc': 'Complementaire fysieke producten die de hoofdaankoop verbeteren',
    'partners.categories.accessories.example1': 'Camera accessoires',
    'partners.categories.accessories.example2': 'Keukengereedschap',
    'partners.categories.accessories.example3': 'Fiets uitrusting',
    'partners.categories.accessories.example4': 'Gaming randapparatuur',
    'partners.categories.accessories.demand': 'Zeer Hoog',
    'partners.categories.accessories.earning': '€15-€100 per artikel',
    'partners.categories.maintenance.title': 'Onderhoud & Support',
    'partners.categories.maintenance.desc': 'Doorlopend onderhoud, support en reparatie services',
    'partners.categories.maintenance.example1': 'Apparaat onderhoud',
    'partners.categories.maintenance.example2': 'Schoonmaakdiensten',
    'partners.categories.maintenance.example3': 'Onderhoudsbeurten',
    'partners.categories.maintenance.example4': 'Technische support',
    'partners.categories.maintenance.demand': 'Gemiddeld',
    'partners.categories.maintenance.earning': '€40-€120 per service',
    'partners.categories.examples': 'Voorbeelden:',
    'partners.categories.demand': 'Vraag:',
'partners.metrics.title': 'Platformstatistieken',
'partners.metrics.subtitle': 'Sluit je aan bij een groeiend netwerk van succesvolle partners',
'partners.metrics.activePartners': 'Actieve Partners',
'partners.metrics.acrossCategories': 'Over alle categorieën',
'partners.metrics.partnerSatisfaction': 'Partnertevredenheid',
'partners.metrics.wouldRecommend': 'Zou ons aanbevelen',
'partners.metrics.avgRating': 'Gem. Partnerbeoordeling',
'partners.metrics.customerSatisfaction': 'Klanttevredenheid',
'partners.metrics.jobsCompleted': 'Voltooide Klussen',
'partners.metrics.thisMonth': 'Deze maand',
'partners.requirements.title': 'Partnervereisten',
'partners.requirements.subtitle': 'We handhaven hoge standaarden om de beste ervaring voor webshops en klanten te garanderen',
'partners.requirements.1': 'Geldige bedrijfsvergunning en verzekering',
'partners.requirements.2': 'Minimaal 4,5-sterren klantbeoordeling',
'partners.requirements.3': 'Bewezen track record in je categorie',
'partners.requirements.4': 'Professionele dienstverlening',
    'partners.requirements.5': 'Duidelijke prijzen en servicebeschrijvingen',
    'partners.requirements.6': 'Toewijding aan AmplifAI kwaliteitsstandaarden',
    'partners.cta.title': 'Klaar om je bedrijf te laten groeien?',
    'partners.cta.subtitle': 'Sluit je aan bij het partnernetwerk van AmplifAI en krijg toegang tot premium klanten die klaar zijn om je diensten te kopen. Geen opstartkosten, alleen resultaten.',
    'partners.cta.button': 'Meld Je Nu Aan',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<'en' | 'nl'>(() => {
    const saved = localStorage.getItem('amplif-language');
    return (saved as 'en' | 'nl') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('amplif-language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};