import React, { createContext, useContext, useState, useEffect } from 'react';

interface LanguageContextType {
  language: 'en' | 'nl';
  setLanguage: (lang: 'en' | 'nl') => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.howItWorks': 'How It Works',
    'nav.examples': 'Examples',
    'nav.merchants': 'For Merchants',
    'nav.partners': 'For Partners',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.joinBeta': 'Join Beta',
    
    // Home Page
    'home.hero.title': 'Turn your Thank-You Page into Instant Revenue.',
    'home.hero.subtitle': 'AmplifAI shows highly relevant add-ons from your catalog and trusted partners—right after purchase.',
    'home.hero.joinBeta': 'Join the Beta',
    'home.hero.seeExamples': 'See Examples',
    'home.seeInAction': 'See it in action',
    'home.demo.subtitle': 'This is how your thank-you page transforms with AmplifAI',
    'home.results.title': 'Results that speak for themselves',
    'home.results.subtitle': 'Our beta merchants are already seeing incredible results with AmplifAI',
    'home.metrics.aov.label': 'Average AOV Increase',
    'home.metrics.aov.desc': 'Typical lift in average order value within 30 days',
    'home.metrics.extraRevenue.label': 'Extra Revenue',
    'home.metrics.extraRevenue.desc': 'Additional revenue per completed order',
    'home.metrics.attachRate.label': 'Attach Rate',
    'home.metrics.attachRate.desc': 'Customers who add at least one offer',
    'home.features.lightning.title': 'Lightning Fast',
    'home.features.lightning.desc': 'Shows up instantly after purchase. No delays, no friction.',
    'home.features.ai.title': 'AI-Powered Matching',
    'home.features.ai.desc': 'Smart algorithms find the perfect complementary products.',
    'home.features.brand.title': 'Brand Safe',
    'home.features.brand.desc': 'Full control over what partners can offer your customers.',
    'home.socialProof.title': 'Trusted by leading e-commerce brands',
    'home.cta.title': 'Ready to transform your thank-you page?',
    'home.cta.subtitle': 'Join hundreds of merchants already boosting their revenue with AmplifAI. Setup takes less than 5 minutes.',
    'home.cta.button': 'Get Started Today',
    
    // Widget Demo
    'widget.title': 'Perfect additions for you',
    'widget.subtitle': 'Curated based on your purchase',
    'widget.orderConfirmed': 'Order Confirmed!',
    'widget.thankYou': 'Thank you for your purchase of the',
    'widget.yourStore': 'Your Store',
    'widget.partners': 'Partners',
    'widget.addInOneClick': 'Add in 1 click',
    'widget.added': 'Added!',
    'widget.byAmplif': 'by AmplifAI',
    
    // Examples Page
    'examples.title': 'Perfect Pairing Examples',
    'examples.subtitle': 'See how AmplifAI creates perfect product pairings across different categories. Each pairing is intelligently matched to maximize value for your customers.',
    'examples.categories.title': 'Offer Categories',
    'examples.categories.subtitle': 'AmplifAI supports multiple types of complementary offers to maximize your revenue potential',
    'examples.tryInDemo': 'Try in Demo',
    'examples.activePairings': 'Active Pairings',
    'examples.examplePairingsTitle': 'Example Pairings',
    'examples.clickToSee': 'Click to see perfect add-ons',
    'examples.perfectAddons': 'Perfect Add-ons',
    'examples.for': 'for',
    'examples.successStories.title': 'Success Stories',
    'examples.successStories.subtitle': 'Real results from merchants using these exact pairings',
    'examples.cta.title': 'Ready to create your own perfect pairings?',
    'examples.cta.subtitle': 'Start with our proven pairing templates and customize them for your store. Our team will help you identify the best opportunities.',
    'examples.cta.startBeta': 'Start Your Beta',
    'examples.cta.tryDemo': 'Try the Demo',
    'examples.grid.subtitle': 'Click any card to see the perfect complementary offers. Each pairing is designed to add genuine value to your customers.',
    
    // How It Works
    'howItWorks.title': 'How AmplifAI Works',
    'howItWorks.subtitle': 'Transform your checkout completion into a revenue opportunity with just 3 simple steps',
    'howItWorks.step1.title': 'Install',
    'howItWorks.step1.desc': 'Add our lightweight snippet to your thank-you page in under 5 minutes',
    'howItWorks.step1.details': 'Add our lightweight widget to your thank-you page with a simple code snippet or install our pre-built extensions for popular platforms like Shopify, WooCommerce, and BigCommerce. Takes less than 5 minutes.',
    'howItWorks.step2.title': 'Match', 
    'howItWorks.step2.desc': 'Our AI analyzes the purchase and shows 3 perfect complementary offers',
    'howItWorks.step2.details': 'Our intelligent matching system analyzes the purchased item, customer history, and your business rules to select the most relevant offers from your catalog and trusted partners. All in real-time.',
    'howItWorks.step3.title': 'Convert',
    'howItWorks.step3.desc': 'Customers add relevant items with 1-2 clicks, boosting your AOV instantly',
    'howItWorks.step3.details': 'Customers can add complementary products with a single click. Payment is processed instantly using their existing checkout session. No re-entering payment details required.',
    'howItWorks.metrics.title': 'Performance Metrics',
    'howItWorks.metrics.subtitle': 'See the impact AmplifAI can have on your business',
    'howItWorks.why.title': 'Why Merchants Choose AmplifAI',
    'howItWorks.faq.title': 'Frequently Asked Questions',
    'howItWorks.faq.subtitle': 'Everything you need to know about implementing AmplifAI',
    'howItWorks.cta.title': 'Ready to get started?',
    'howItWorks.cta.subtitle': 'Join the beta and start generating additional revenue from day one. Setup takes less than 10 minutes.',
    'howItWorks.cta.button': 'Talk to Us',
    
    // About Page
    'about.title': 'About AmplifAI',
    'about.subtitle': 'We\'re revolutionizing post-purchase experiences with intelligent product recommendations',
    'about.mission.title': 'Our Mission',
    'about.mission.text': 'AmplifAI transforms the often-overlooked thank-you page into a powerful revenue generator. We believe that the moment after purchase is when customers are most receptive to complementary offers—and we\'ve built the technology to capitalize on that opportunity.',
    'about.story.title': 'Our Story',
    'about.story.text': 'Founded by e-commerce veterans who experienced the frustration of missed revenue opportunities firsthand, AmplifAI was born from a simple observation: customers who just made a purchase are in a buying mindset, but most retailers completely waste this golden moment.',
    'about.technology.title': 'Our Technology',
    'about.technology.text': 'Our proprietary AI analyzes purchase patterns, customer behavior, and product relationships to surface the most relevant add-on offers. We don\'t just show random products—we show the perfect complement to what was just purchased.',
    'about.team.title': 'Built by E-commerce Experts',
    'about.team.text': 'Our team combines deep e-commerce experience with cutting-edge AI expertise. We\'ve helped scale multiple online retailers and understand exactly what merchants need to succeed.',
    
    // Contact
    'contact.title': 'Join the Beta',
    'contact.subtitle': 'Ready to transform your thank-you page or join our partner network? Tell us about your business and let\'s get started.',
    'contact.merchant': 'I\'m a Webshop',
    'contact.partner': 'I\'m a Partner',
    'contact.name': 'Name',
    'contact.email': 'Work Email',
    'contact.company': 'Company',
    'contact.website': 'Website',
    'contact.platform': 'Platform',
    'contact.category': 'Category',
    'contact.submit': 'Count me in',
    'contact.success': 'Thanks! We\'ll reach out within 2 business days.',
    'contact.successTitle': 'Application submitted!',
    'contact.iam': 'I am a',
    'contact.merchantDesc': 'I sell products online',
    'contact.partnerDesc': 'I provide services',
    'contact.selectPlatform': 'Select your platform',
    'contact.selectCategory': 'Select your category',
    'contact.errorMsg': 'Please try again or contact us directly.',
    
    // Payment Modal
    'payment.title': 'Complete Your Purchase',
    'payment.subtitle': 'Choose your preferred payment method',
    'payment.card': 'Credit/Debit Card',
    'payment.paypal': 'PayPal',
    'payment.applepay': 'Apple Pay',
    'payment.googlepay': 'Google Pay',
    'payment.total': 'Total',
    'payment.confirm': 'Confirm Payment',
    'payment.processing': 'Processing...',
    'payment.success': 'Payment Successful!',
    'payment.successMsg': 'Your order has been confirmed. You will receive a confirmation email shortly.',
    'payment.cancel': 'Cancel',
    
    // Partner Modal
    'partner.bookAppointment': 'Book Your Appointment',
    'partner.availableTimes': 'Available times for',
    'partner.bookingBtn': 'Book Appointment',
    'partner.selectDateTime': 'Select Date & Time',
    'partner.addToCart': 'Add to Cart',
    'partner.appointmentBooked': 'Appointment Booked!',
    'partner.addedToCart': 'Added to Cart!',
    'partner.soldBy': 'Sold by Your Store',
    'partner.partnerBy': 'Partner:',
    'partner.reviews': 'reviews',
    
    // Footer
    'footer.company': 'Company',
    'footer.blog': 'Blog',
    'footer.careers': 'Careers',
    'footer.support': 'Support',
    'footer.help': 'Help Center',
    'footer.status': 'Status',
    'footer.legal': 'Legal',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.cookies': 'Cookie Policy',
    'footer.madeWithLove': 'Made with ❤️ for ambitious merchants',
    'footer.tagline': 'Turn your thank-you page into instant revenue with intelligent product recommendations.',

    // Categories
    'category.accessory': 'Accessory',
    'category.service': 'Service',
    'category.warranty': 'Warranty',
    'category.subscription': 'Subscription',
    'category.accessories': 'Accessories',
    'category.services': 'Services',
    'category.warranties': 'Warranties',
    'category.subscriptions': 'Subscriptions',

    // Common
    'common.by': 'by',
    'common.submitting': 'Submitting...',
    'common.error': 'Something went wrong',

    // Not Found
    'notfound.title': 'Oops! Page not found',
    'notfound.back': 'Return to Home',

    // Merchants Page
    'merchants.hero.title': 'For <span class="gradient-text">Merchants</span>',
    'merchants.hero.subtitle': 'Turn your thank-you page into a revenue powerhouse. Add 15-40% to your average order value with zero operational overhead and complete brand control.',
    'merchants.hero.startTrial': 'Start Your Free Trial',
    'merchants.valueProps.title': 'Why Merchants Love AmplifAI',
    'merchants.valueProps.subtitle': 'Everything you need to generate additional revenue without additional work',
    'merchants.valueProps.foundMargin.title': 'Found Margin, Zero Extra Ops',
    'merchants.valueProps.foundMargin.desc': 'Generate additional revenue without inventory, shipping, or customer service overhead. Pure margin on every add-on sale.',
    'merchants.valueProps.brandSafe.title': 'Brand-Safe Controls',
    'merchants.valueProps.brandSafe.desc': 'Full control over partner offers with allow/deny lists, category restrictions, and brand guidelines. Maintain your reputation.',
    'merchants.valueProps.fastGoLive.title': '1-Day Go-Live, 7-Day ROI',
    'merchants.valueProps.fastGoLive.desc': 'Quick integration with immediate results. Most merchants see positive ROI within their first week of going live.',
    'merchants.valueProps.aiPowered.title': 'AI-Powered Optimization',
    'merchants.valueProps.aiPowered.desc': 'Our machine learning continuously improves offer relevance and timing to maximize conversion rates.',
    'merchants.valueProps.analytics.title': 'Comprehensive Analytics',
    'merchants.valueProps.analytics.desc': 'Real-time dashboard showing performance metrics, revenue attribution, and optimization opportunities.',
    'merchants.valueProps.integration.title': 'Seamless Integration',
    'merchants.valueProps.integration.desc': 'Works with all major e-commerce platforms. No disruption to your existing checkout flow or customer experience.',
    'merchants.results.title': 'Merchant Results',
    'merchants.results.subtitle': 'Real results from merchants using AmplifAI',
    'merchants.results.aovIncrease': 'Avg AOV Increase',
    'merchants.results.aovDesc': 'Typical lift after 30 days',
    'merchants.results.attachRate': 'Attach Rate',
    'merchants.results.attachDesc': 'Customers adding offers',
    'merchants.results.revenuePerOrder': 'Revenue Per Order',
    'merchants.results.revenueDesc': 'Additional earnings',
    'merchants.results.daysToROI': 'Days to ROI',
    'merchants.results.roiDesc': 'Break-even timeline',
    'merchants.integration.title': 'Getting Started Is Simple',
    'merchants.integration.subtitle': 'From setup to first sale in under 30 minutes',
    'merchants.integration.step1.title': 'Connect Your Store',
    'merchants.integration.step1.desc': 'Install our lightweight snippet or platform-specific app',
    'merchants.integration.step1.timeline': '5 minutes',
    'merchants.integration.step2.title': 'Configure Preferences',
    'merchants.integration.step2.desc': 'Set your brand guidelines and partner preferences',
    'merchants.integration.step2.timeline': '10 minutes',
    'merchants.integration.step3.title': 'Go Live',
    'merchants.integration.step3.desc': 'Start showing relevant offers to your customers',
    'merchants.integration.step3.timeline': 'Instant',
    'merchants.integration.step4.title': 'See Results',
    'merchants.integration.step4.desc': 'Monitor performance and optimize your strategy',
    'merchants.integration.step4.timeline': '7 days',
    'merchants.platforms.title': 'Works With Your Platform',
    'merchants.platforms.subtitle': 'Native integrations and universal compatibility',
    'merchants.platforms.merchants': 'merchants',
    'merchants.faq.title': 'Frequently Asked Questions',
    'merchants.faq.subtitle': 'Everything merchants need to know about AmplifAI',
    'merchants.faq.platforms.q': 'What e-commerce platforms do you support?',
    'merchants.faq.platforms.a': 'AmplifAI works with all major platforms including Shopify, WooCommerce, Magento, BigCommerce, Salesforce Commerce Cloud, and custom builds. We provide native integrations and universal JavaScript snippets.',
    'merchants.faq.refunds.q': 'How do refunds work?',
    'merchants.faq.refunds.a': 'Our refund coupling system automatically handles add-on refunds when the original item is returned. If customers return the main product, any related add-ons are refunded proportionally, maintaining complete transaction integrity.',
    'merchants.faq.control.q': 'What control do I have over partner offers?',
    'merchants.faq.control.a': 'Complete control. You can set category restrictions, maintain allow/deny lists for specific partners, require approval for new offers, and ensure all partner communications follow your brand guidelines.',
    'merchants.faq.vetting.q': 'How are partners vetted?',
    'merchants.faq.vetting.a': 'All partners go through our comprehensive KYC process including business license verification, insurance checks, customer review analysis, and financial standing assessment. Only high-quality, reliable partners are approved.',
    'merchants.faq.revenue.q': 'What\'s the revenue split?',
    'merchants.faq.revenue.a': 'You earn a commission on all partner sales generated through your customers, typically 10-25% depending on the service category. There are no upfront costs or monthly fees - you only pay when you earn.',
    'merchants.faq.design.q': 'Can I customize the widget design?',
    'merchants.faq.design.a': 'Yes, the widget is fully customizable to match your brand colors, fonts, and styling. We also offer A/B testing tools to optimize the design for maximum conversion.',
    'merchants.cta.title': 'Ready to boost your revenue?',
    'merchants.cta.subtitle': 'Join hundreds of merchants already generating additional revenue with AmplifAI. No setup costs, no risk, pure upside.',
    'merchants.cta.button': 'Talk to Us',

    // Partners Page
    'partners.hero.title': 'For <span class="gradient-text">Partners</span>',
    'partners.hero.subtitle': 'Reach new customers at the perfect moment - right after they\'ve made a purchase. Join our network and grow your business with high-intent, qualified leads.',
    'partners.hero.joinNetwork': 'Join Our Network',
  },
  nl: {
    // Navigation
    'nav.home': 'Home',
    'nav.howItWorks': 'Hoe Het Werkt',
    'nav.examples': 'Voorbeelden',
    'nav.merchants': 'Voor Merchants',
    'nav.partners': 'Voor Partners',
    'nav.about': 'Over Ons',
    'nav.contact': 'Contact',
    'nav.joinBeta': 'Meld Je Aan',
    
    // Home Page
    'home.hero.title': 'Maak van je Bedankpagina Direct Omzet.',
    'home.hero.subtitle': 'AmplifAI toont zeer relevante add-ons uit je catalogus en vertrouwde partners—direct na de aankoop.',
    'home.hero.joinBeta': 'Meld Je Aan voor Beta',
    'home.hero.seeExamples': 'Bekijk Voorbeelden',
    'home.seeInAction': 'Zie het in actie',
    'home.demo.subtitle': 'Zo transformeert je bedankpagina met AmplifAI',
    'home.results.title': 'Resultaten die voor zich spreken',
    'home.results.subtitle': 'Onze beta merchants zien al ongelooflijke resultaten met AmplifAI',
    'home.metrics.aov.label': 'Gemiddelde AOV Verhoging',
    'home.metrics.aov.desc': 'Typische stijging in gemiddelde bestelwaarde binnen 30 dagen',
    'home.metrics.extraRevenue.label': 'Extra Omzet',
    'home.metrics.extraRevenue.desc': 'Aanvullende omzet per voltooide bestelling',
    'home.metrics.attachRate.label': 'Bijkooppercentage',
    'home.metrics.attachRate.desc': 'Klanten die minstens één aanbieding toevoegen',
    'home.features.lightning.title': 'Bliksemnel',
    'home.features.lightning.desc': 'Verschijnt direct na aankoop. Geen vertraging, geen wrijving.',
    'home.features.ai.title': 'AI-Aangedreven Matching',
    'home.features.ai.desc': 'Slimme algoritmes vinden de perfecte complementaire producten.',
    'home.features.brand.title': 'Merkveilig',
    'home.features.brand.desc': 'Volledige controle over wat partners aan je klanten kunnen aanbieden.',
    'home.socialProof.title': 'Vertrouwd door toonaangevende e-commerce merken',
    'home.cta.title': 'Klaar om je bedankpagina te transformeren?',
    'home.cta.subtitle': 'Sluit je aan bij honderden merchants die al hun omzet verhogen met AmplifAI. Setup duurt minder dan 5 minuten.',
    'home.cta.button': 'Begin Vandaag Nog',
    
    // Widget Demo
    'widget.title': 'Perfecte toevoegingen voor jou',
    'widget.subtitle': 'Geselecteerd op basis van je aankoop',
    'widget.orderConfirmed': 'Bestelling Bevestigd!',
    'widget.thankYou': 'Bedankt voor je aankoop van de',
    'widget.yourStore': 'Jouw Winkel',
    'widget.partners': 'Partners',
    'widget.addInOneClick': 'Toevoegen met 1 klik',
    'widget.added': 'Toegevoegd!',
    'widget.byAmplif': 'door AmplifAI',
    
    // Examples Page
    'examples.title': 'Perfecte Combinatie Voorbeelden',
    'examples.subtitle': 'Zie hoe AmplifAI perfecte productcombinaties creëert in verschillende categorieën. Elke combinatie is intelligent gekozen om de waarde voor je klanten te maximaliseren.',
    'examples.categories.title': 'Aanbod Categorieën',
    'examples.categories.subtitle': 'AmplifAI ondersteunt meerdere soorten complementaire aanbiedingen om je omzetpotentieel te maximaliseren',
    'examples.tryInDemo': 'Probeer in Demo',
    'examples.activePairings': 'Actieve Combinaties',
    'examples.examplePairingsTitle': 'Voorbeeld Combinaties',
    'examples.clickToSee': 'Klik om perfecte add-ons te zien',
    'examples.perfectAddons': 'Perfecte Add-ons',
    'examples.for': 'voor',
    'examples.successStories.title': 'Succesverhalen',
    'examples.successStories.subtitle': 'Echte resultaten van merchants die precies deze combinaties gebruiken',
    'examples.cta.title': 'Klaar om je eigen perfecte combinaties te maken?',
    'examples.cta.subtitle': 'Begin met onze bewezen combinatiesjablonen en pas ze aan voor je winkel. Ons team helpt je de beste kansen te identificeren.',
    'examples.cta.startBeta': 'Start Je Beta',
    'examples.cta.tryDemo': 'Probeer de Demo',
    'examples.grid.subtitle': 'Klik op een kaart om de perfecte complementaire aanbiedingen te zien. Elke combinatie is ontworpen om echte waarde toe te voegen voor je klanten.',
    
    // How It Works
    'howItWorks.title': 'Hoe AmplifAI Werkt',
    'howItWorks.subtitle': 'Transformeer je checkout-voltooiing in een omzetkans met maar 3 eenvoudige stappen',
    'howItWorks.step1.title': 'Installeren',
    'howItWorks.step1.desc': 'Voeg ons lichtgewicht snippet toe aan je bedankpagina in minder dan 5 minuten',
    'howItWorks.step1.details': 'Voeg onze lichtgewicht widget toe aan je bedankpagina met een eenvoudig code-snippet of installeer onze kant-en-klare extensies voor populaire platforms zoals Shopify, WooCommerce en BigCommerce. Duurt minder dan 5 minuten.',
    'howItWorks.step2.title': 'Matchen',
    'howItWorks.step2.desc': 'Onze AI analyseert de aankoop en toont 3 perfecte complementaire aanbiedingen',
    'howItWorks.step2.details': 'Ons intelligente matchingsysteem analyseert het gekochte artikel, klantgeschiedenis en je bedrijfsregels om de meest relevante aanbiedingen te selecteren uit je catalogus en vertrouwde partners. Alles in realtime.',
    'howItWorks.step3.title': 'Converteren',
    'howItWorks.step3.desc': 'Klanten voegen relevante items toe met 1-2 klikken, wat je AOV direct verhoogt',
    'howItWorks.step3.details': 'Klanten kunnen complementaire producten toevoegen met een enkele klik. Betaling wordt direct verwerkt via hun bestaande checkout-sessie. Geen hernieuw invoeren van betalingsgegevens vereist.',
    'howItWorks.metrics.title': 'Prestatie Indicatoren',
    'howItWorks.metrics.subtitle': 'Zie de impact die AmplifAI kan hebben op je bedrijf',
    'howItWorks.why.title': 'Waarom Merchants Kiezen voor AmplifAI',
    'howItWorks.faq.title': 'Veelgestelde Vragen',
    'howItWorks.faq.subtitle': 'Alles wat je moet weten over het implementeren van AmplifAI',
    'howItWorks.cta.title': 'Klaar om te beginnen?',
    'howItWorks.cta.subtitle': 'Meld je aan voor de beta en begin vanaf dag één extra omzet te genereren. Setup duurt minder dan 10 minuten.',
    'howItWorks.cta.button': 'Praat Met Ons',
    
    // About Page
    'about.title': 'Over AmplifAI',
    'about.subtitle': 'Wij revolutioneren na-aankoop ervaringen met intelligente productaanbevelingen',
    'about.mission.title': 'Onze Missie',
    'about.mission.text': 'AmplifAI transformeert de vaak over het hoofd geziene bedankpagina in een krachtige omzetgenerator. Wij geloven dat het moment na de aankoop is wanneer klanten het meest ontvankelijk zijn voor complementaire aanbiedingen—en wij hebben de technologie gebouwd om van die kans gebruik te maken.',
    'about.story.title': 'Ons Verhaal',
    'about.story.text': 'Opgericht door e-commerce veteranen die de frustratie van gemiste omzetkansen aan den lijve hebben ondervonden, werd AmplifAI geboren uit een eenvoudige observatie: klanten die net een aankoop hebben gedaan bevinden zich in een koopmentaliteit, maar de meeste retailers verspillen dit gouden moment volledig.',
    'about.technology.title': 'Onze Technologie',
    'about.technology.text': 'Onze eigenlijke AI analyseert aankooppatronen, klantgedrag en productrelaties om de meest relevante add-on aanbiedingen naar boven te brengen. We tonen niet zomaar willekeurige producten—we tonen de perfecte aanvulling op wat net is gekocht.',
    'about.team.title': 'Gebouwd door E-commerce Experts',
    'about.team.text': 'Ons team combineert diepe e-commerce ervaring met geavanceerde AI-expertise. We hebben meerdere online retailers geholpen schalen en begrijpen precies wat merchants nodig hebben om te slagen.',
    
    // Contact
    'contact.title': 'Meld Je Aan',
    'contact.subtitle': 'Klaar om je bedankpagina te transformeren of je aan te sluiten bij ons partnernetwerk? Vertel ons over je bedrijf en laten we beginnen.',
    'contact.merchant': 'Ik ben een Webshop',
    'contact.partner': 'Ik ben een Partner',
    'contact.name': 'Naam',
    'contact.email': 'Werk E-mail',
    'contact.company': 'Bedrijf',
    'contact.website': 'Website',
    'contact.platform': 'Platform',
    'contact.category': 'Categorie',
    'contact.submit': 'Teken Mij In',
    'contact.success': 'Bedankt! We nemen binnen 2 werkdagen contact op.',
    'contact.successTitle': 'Aanmelding ingediend!',
    'contact.iam': 'Ik ben een',
    'contact.merchantDesc': 'Ik verkoop producten online',
    'contact.partnerDesc': 'Ik bied diensten aan',
    'contact.selectPlatform': 'Selecteer je platform',
    'contact.selectCategory': 'Selecteer je categorie',
    'contact.errorMsg': 'Probeer het opnieuw of neem direct contact met ons op.',
    
    // Payment Modal
    'payment.title': 'Voltooi Je Aankoop',
    'payment.subtitle': 'Kies je voorkeursbetaalmethode',
    'payment.card': 'Credit/Debit Card',
    'payment.paypal': 'PayPal',
    'payment.applepay': 'Apple Pay',
    'payment.googlepay': 'Google Pay',
    'payment.total': 'Totaal',
    'payment.confirm': 'Bevestig Betaling',
    'payment.processing': 'Verwerken...',
    'payment.success': 'Betaling Succesvol!',
    'payment.successMsg': 'Je bestelling is bevestigd. Je ontvangt binnenkort een bevestigingsmail.',
    'payment.cancel': 'Annuleren',
    
    // Partner Modal
    'partner.bookAppointment': 'Boek Je Afspraak',
    'partner.availableTimes': 'Beschikbare tijden voor',
    'partner.bookingBtn': 'Boek Afspraak',
    'partner.selectDateTime': 'Selecteer Datum & Tijd',
    'partner.addToCart': 'Toevoegen aan Winkelwagen',
    'partner.appointmentBooked': 'Afspraak Geboekt!',
    'partner.addedToCart': 'Toegevoegd aan Winkelwagen!',
    'partner.soldBy': 'Verkocht door Jouw Winkel',
    'partner.partnerBy': 'Partner:',
    'partner.reviews': 'beoordelingen',
    
    // Footer
    'footer.company': 'Bedrijf',
    'footer.blog': 'Blog',
    'footer.careers': 'careers',
    'footer.support': 'Ondersteuning',
    'footer.help': 'Helpcentrum',
    'footer.status': 'Status',
    'footer.legal': 'Legaal',
    'footer.privacy': 'Privacybeleid',
    'footer.terms': 'Servicevoorwaarden',
    'footer.cookies': 'Cookiebeleid',
    'footer.madeWithLove': 'Gemaakt met ❤️ voor ambitieuze merchants',
    'footer.tagline': 'Transformeer je bedankpagina in directe omzet met intelligente productaanbevelingen.',

    // Categories
    'category.accessory': 'Accessoire',
    'category.service': 'Service',
    'category.warranty': 'Garantie',
    'category.subscription': 'Abonnement',
    'category.accessories': 'Accessoires',
    'category.services': 'Services',
    'category.warranties': 'Garanties',
    'category.subscriptions': 'Abonnementen',

    // Common
    'common.by': 'door',
    'common.submitting': 'Versturen...',
    'common.error': 'Er ging iets mis',

    // Not Found
    'notfound.title': 'Oops! Pagina niet gevonden',
    'notfound.back': 'Terug naar Home',

    // Merchants Page
    'merchants.hero.title': 'Voor <span class="gradient-text">Merchants</span>',
    'merchants.hero.subtitle': 'Transformeer je bedankpagina in een omzet krachtpatser. Voeg 15-40% toe aan je gemiddelde bestelwaarde met nul operationele overhead en volledige merkcontrole.',
    'merchants.hero.startTrial': 'Start Je Gratis Proefperiode',
    'merchants.valueProps.title': 'Waarom Merchants Dol Zijn op AmplifAI',
    'merchants.valueProps.subtitle': 'Alles wat je nodig hebt om extra omzet te genereren zonder extra werk',
    'merchants.valueProps.foundMargin.title': 'Gevonden Marge, Nul Extra Ops',
    'merchants.valueProps.foundMargin.desc': 'Genereer extra omzet zonder voorraad, verzending of klantenservice overhead. Pure marge op elke add-on verkoop.',
    'merchants.valueProps.brandSafe.title': 'Merkveilige Controles',
    'merchants.valueProps.brandSafe.desc': 'Volledige controle over partneraanbiedingen met toestaan/weigeren lijsten, categorierestricties en merkrichtlijnen. Behoud je reputatie.',
    'merchants.valueProps.fastGoLive.title': '1-Dag Go-Live, 7-Dag ROI',
    'merchants.valueProps.fastGoLive.desc': 'Snelle integratie met directe resultaten. De meeste merchants zien positieve ROI binnen hun eerste week live.',
    'merchants.valueProps.aiPowered.title': 'AI-Aangedreven Optimalisatie',
    'merchants.valueProps.aiPowered.desc': 'Onze machine learning verbetert continu aanbiedingrelevantie en timing om conversiepercentages te maximaliseren.',
    'merchants.valueProps.analytics.title': 'Uitgebreide Analytics',
    'merchants.valueProps.analytics.desc': 'Realtime dashboard met prestatie-indicatoren, omzet-attributie en optimalisatiekansen.',
    'merchants.valueProps.integration.title': 'Naadloze Integratie',
    'merchants.valueProps.integration.desc': 'Werkt met alle grote e-commerce platforms. Geen verstoring van je bestaande checkout-flow of klantervaring.',
    'merchants.results.title': 'Merchant Resultaten',
    'merchants.results.subtitle': 'Echte resultaten van merchants die AmplifAI gebruiken',
    'merchants.results.aovIncrease': 'Gem AOV Verhoging',
    'merchants.results.aovDesc': 'Typische stijging na 30 dagen',
    'merchants.results.attachRate': 'Bijkooppercentage',
    'merchants.results.attachDesc': 'Klanten die aanbiedingen toevoegen',
    'merchants.results.revenuePerOrder': 'Omzet Per Bestelling',
    'merchants.results.revenueDesc': 'Extra verdiensten',
    'merchants.results.daysToROI': 'Dagen Tot ROI',
    'merchants.results.roiDesc': 'Break-even tijdlijn',
    'merchants.integration.title': 'Beginnen Is Eenvoudig',
    'merchants.integration.subtitle': 'Van setup tot eerste verkoop in minder dan 30 minuten',
    'merchants.integration.step1.title': 'Verbind Je Winkel',
    'merchants.integration.step1.desc': 'Installeer ons lichtgewicht snippet of platform-specifieke app',
    'merchants.integration.step1.timeline': '5 minuten',
    'merchants.integration.step2.title': 'Configureer Voorkeuren',
    'merchants.integration.step2.desc': 'Stel je merkrichtlijnen en partnervoorkeuren in',
    'merchants.integration.step2.timeline': '10 minuten',
    'merchants.integration.step3.title': 'Ga Live',
    'merchants.integration.step3.desc': 'Begin relevante aanbiedingen te tonen aan je klanten',
    'merchants.integration.step3.timeline': 'Direct',
    'merchants.integration.step4.title': 'Zie Resultaten',
    'merchants.integration.step4.desc': 'Bewaak prestaties en optimaliseer je strategie',
    'merchants.integration.step4.timeline': '7 dagen',
    'merchants.platforms.title': 'Werkt Met Je Platform',
    'merchants.platforms.subtitle': 'Native integraties en universele compatibiliteit',
    'merchants.platforms.merchants': 'merchants',
    'merchants.faq.title': 'Veelgestelde Vragen',
    'merchants.faq.subtitle': 'Alles wat merchants moeten weten over AmplifAI',
    'merchants.faq.platforms.q': 'Welke e-commerce platforms ondersteunen jullie?',
    'merchants.faq.platforms.a': 'AmplifAI werkt met alle grote platforms waaronder Shopify, WooCommerce, Magento, BigCommerce, Salesforce Commerce Cloud en aangepaste builds. We bieden native integraties en universele JavaScript snippets.',
    'merchants.faq.refunds.q': 'Hoe werken restituties?',
    'merchants.faq.refunds.a': 'Ons restitutiekoppelingssysteem handelt automatisch add-on restituties af wanneer het oorspronkelijke artikel wordt geretourneerd. Als klanten het hoofdproduct retourneren, worden gerelateerde add-ons proportioneel gerestitueerd, waarbij volledige transactie-integriteit behouden blijft.',
    'merchants.faq.control.q': 'Welke controle heb ik over partneraanbiedingen?',
    'merchants.faq.control.a': 'Volledige controle. Je kunt categorierestricties instellen, toestaan/weigeren lijsten onderhouden voor specifieke partners, goedkeuring vereisen voor nieuwe aanbiedingen, en ervoor zorgen dat alle partnercommunicatie je merkrichtlijnen volgt.',
    'merchants.faq.vetting.q': 'Hoe worden partners gescreend?',
    'merchants.faq.vetting.a': 'Alle partners doorlopen ons uitgebreide KYC-proces inclusief verificatie van bedrijfslicenties, verzekeringscontroles, analyse van klantrecensies en beoordeling van financiële status. Alleen hoogkwaliteit, betrouwbare partners worden goedgekeurd.',
    'merchants.faq.revenue.q': 'Wat is de omzetverdeling?',
    'merchants.faq.revenue.a': 'Je verdient een commissie op alle partnerverkopen gegenereerd via je klanten, doorgaans 10-25% afhankelijk van de dienstcategorie. Er zijn geen upfront kosten of maandelijkse vergoedingen - je betaalt alleen wanneer je verdient.',
    'merchants.faq.design.q': 'Kan ik het widget ontwerp aanpassen?',
    'merchants.faq.design.a': 'Ja, de widget is volledig aanpasbaar aan je merkkleuren, lettertypen en styling. We bieden ook A/B-testtools om het ontwerp te optimaliseren voor maximale conversie.',
    'merchants.cta.title': 'Klaar om je omzet te verhogen?',
    'merchants.cta.subtitle': 'Sluit je aan bij honderden merchants die al extra omzet genereren met AmplifAI. Geen setup kosten, geen risico, puur voordeel.',
    'merchants.cta.button': 'Praat Met Ons',

    // Partners Page
    'partners.hero.title': 'Voor <span class="gradient-text">Partners</span>',
    'partners.hero.subtitle': 'Bereik nieuwe klanten op het perfecte moment - direct nadat ze een aankoop hebben gedaan. Sluit je aan bij ons netwerk en laat je bedrijf groeien met hoogkwalificeerde, geïnteresseerde leads.',
    'partners.hero.joinNetwork': 'Meld Je Aan Bij Ons Netwerk',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<'en' | 'nl'>(() => {
    const saved = localStorage.getItem('amplif-language');
    return (saved as 'en' | 'nl') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('amplif-language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};